pub mod rand_poisson;
pub mod randn;
pub mod random;
pub mod spark_abs;
pub mod spark_bin;
pub mod spark_bround;
pub mod spark_ceil_floor;
pub mod spark_conv;
pub mod spark_div;
pub mod spark_signum;
pub mod spark_try_add;
pub mod spark_try_div;
pub mod spark_try_mod;
pub mod spark_try_mult;
pub mod spark_try_subtract;
pub mod spark_unhex;
mod utils;
mod xorshift;
