/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FetchScanTasksRequest {
    /// An opaque string provided by the REST server that represents a unit of work to produce file scan tasks for scan planning. This allows clients to fetch tasks across multiple requests to accommodate large result sets.
    #[serde(rename = "plan-task")]
    pub plan_task: String,
}

impl FetchScanTasksRequest {
    pub fn new(plan_task: String) -> FetchScanTasksRequest {
        FetchScanTasksRequest {
            plan_task,
        }
    }
}

