/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Type {
    PrimitiveType(String),
    StructType(Box<models::StructType>),
    ListType(Box<models::ListType>),
    MapType(Box<models::MapType>),
}

impl Default for Type {
    fn default() -> Self {
        Self::PrimitiveType(Default::default())
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "struct")]
    Struct,
    #[serde(rename = "list")]
    List,
    #[serde(rename = "map")]
    Map,
}

impl Default for Type {
    fn default() -> Type {
        Self::Struct
    }
}
