/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetPartitionStatisticsUpdate {
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<String>,
    #[serde(rename = "partition-statistics")]
    pub partition_statistics: Box<models::PartitionStatisticsFile>,
}

impl SetPartitionStatisticsUpdate {
    pub fn new(partition_statistics: models::PartitionStatisticsFile) -> SetPartitionStatisticsUpdate {
        SetPartitionStatisticsUpdate {
            action: None,
            partition_statistics: Box::new(partition_statistics),
        }
    }
}

