/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatisticsFile {
    #[serde(rename = "snapshot-id")]
    pub snapshot_id: i64,
    #[serde(rename = "statistics-path")]
    pub statistics_path: String,
    #[serde(rename = "file-size-in-bytes")]
    pub file_size_in_bytes: i64,
    #[serde(rename = "file-footer-size-in-bytes")]
    pub file_footer_size_in_bytes: i64,
    #[serde(rename = "blob-metadata")]
    pub blob_metadata: Vec<models::BlobMetadata>,
}

impl StatisticsFile {
    pub fn new(
        snapshot_id: i64,
        statistics_path: String,
        file_size_in_bytes: i64,
        file_footer_size_in_bytes: i64,
        blob_metadata: Vec<models::BlobMetadata>,
    ) -> StatisticsFile {
        StatisticsFile {
            snapshot_id,
            statistics_path,
            file_size_in_bytes,
            file_footer_size_in_bytes,
            blob_metadata,
        }
    }
}
