/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StructField {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "type")]
    pub r#type: Box<models::Type>,
    #[serde(rename = "required")]
    pub required: bool,
    #[serde(rename = "doc", skip_serializing_if = "Option::is_none")]
    pub doc: Option<String>,
    #[serde(rename = "initial-default", skip_serializing_if = "Option::is_none")]
    pub initial_default: Option<Box<models::PrimitiveTypeValue>>,
    #[serde(rename = "write-default", skip_serializing_if = "Option::is_none")]
    pub write_default: Option<Box<models::PrimitiveTypeValue>>,
}

impl StructField {
    pub fn new(id: i32, name: String, r#type: models::Type, required: bool) -> StructField {
        StructField {
            id,
            name,
            r#type: Box::new(r#type),
            required,
            doc: None,
            initial_default: None,
            write_default: None,
        }
    }
}
