[package]
name = "sail-open-api"
version = { workspace = true }
edition = { workspace = true }

[lints]
workspace = true

[dependencies]
progenitor-client = { workspace = true }
futures = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
base64 = { workspace = true }
rand = { workspace = true }
regress = { workspace = true }

[build-dependencies]
progenitor = { workspace = true }
prettyplease = { workspace = true }
serde_yaml = { workspace = true }
syn = { workspace = true }