name: Rust setup
description: Prepare Rust build environment and build cache
inputs:
  cache-key:
    description: Cache key prefix (e.g., 'rust-tests', 'rust-lint', or 'rust-build')
    required: true
  install-testing-tools:
    description: Whether to install testing tools (grcov, nextest, llvm-tools-preview)
    default: "true"
  install-nightly-toolchain:
    description: Whether to install the Rust nightly toolchain
    default: "false"
runs:
  using: composite
  steps:
    - name: Install protoc
      uses: arduino/setup-protoc@v3
      with:
        # Set the GitHub token to avoid rate limiting when using the GitHub API
        # to get the latest protoc release.
        repo-token: ${{ github.token }}

    # The Rust stable toolchain is likely installed already, but we need to check for updates.
    - name: Install Rust toolchain (stable)
      run: |
        if [[ "${{ inputs.install-testing-tools }}" == "true" ]]; then
          rustup toolchain install stable --profile default --component llvm-tools-preview
        else
          rustup toolchain install stable --profile default
        fi
      shell: bash

    # The Rust nightly toolchain is needed for features used in e.g. code formatting.
    - name: Install Rust toolchain (nightly)
      if: ${{ inputs.install-nightly-toolchain == 'true' }}
      run: |
        rustup toolchain install nightly --profile default
      shell: bash

    - name: Install grcov
      if: ${{ inputs.install-testing-tools == 'true' }}
      uses: taiki-e/install-action@grcov

    - name: Install cargo-nextest
      if: ${{ inputs.install-testing-tools == 'true' }}
      uses: taiki-e/install-action@nextest

    - name: Show versions
      id: versions
      run: |
        set -x
        protoc --version
        python -V
        rustc -vV
        set +x
        rust_release="$(rustc -vV | sed -ne 's/^release: *//p')"
        echo "rust_release=${rust_release}" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Configure cache
      id: config
      # In the script below, the outer heredoc is interpreted by the shell,
      # while the inner heredoc is interpreted by the `GITHUB_OUTPUT` file.
      run: |
        cat <<EOF >> "$GITHUB_OUTPUT"
        path<<TEXT
        ~/.cargo/bin/
        ~/.cargo/registry/index/
        ~/.cargo/registry/cache/
        ~/.cargo/git/
        target/**/build/
        target/**/deps/
        target/**/.fingerprint/
        TEXT
        EOF
        echo "label=${{ steps.versions.outputs.rust_release }}-${{ runner.os }}-${{ runner.arch }}" >> "$GITHUB_OUTPUT"
        echo "hash=${{ hashFiles('**/Cargo.toml', 'Cargo.lock') }}" >> "$GITHUB_OUTPUT"
      shell: bash

    - uses: actions/cache@v4
      if: ${{ github.event_name == 'push' }}
      with:
        path: ${{ steps.config.outputs.path }}
        key: ${{ inputs.cache-key }}-${{ steps.config.outputs.label }}-${{ steps.config.outputs.hash }}

    # We save the cache only for push events, so that more cache space can be reserved
    # for the default branch and cache eviction is less likely to happen.
    # We always use caches of the default branch for pull requests. The cache is still useful
    # if the dependencies do not differ too much between the default branch and the feature branch.
    - uses: actions/cache/restore@v4
      if: ${{ github.event_name != 'push' }}
      with:
        path: ${{ steps.config.outputs.path }}
        key: ${{ inputs.cache-key }}-${{ steps.config.outputs.label }}-${{ steps.config.outputs.hash }}
        restore-keys: |
          ${{ inputs.cache-key }}-${{ steps.config.outputs.label }}-

    # Incremental compilation is not beneficial for CI builds.
    # So we turn it off to speed up the build and reduce the cache size.
    # This step is skipped for Claude Code setup.
    - name: Turn off incremental compilation
      if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
      run: |
        echo CARGO_INCREMENTAL=0 >> "$GITHUB_ENV"
      shell: bash

    # Set debug level to 0 for dev profile if not already set to reduce build size and time
    - name: Configure dev profile debug level
      run: |
        if [[ ! -v CARGO_PROFILE_DEV_DEBUG ]]; then
          echo "CARGO_PROFILE_DEV_DEBUG=0" >> $GITHUB_ENV
        fi
      shell: bash
