codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true
    manual_trigger: true

comment:
  layout: "header, diff, flags, components, tree"
  show_carryforward_flags: true

ignore:
  - "crates/sail-gold-test"

flag_management:
  default_rules:
    carryforward: false
  statuses:
    - type: project
      target: 0
      informational: true
    - type: patch
      target: 0
      informational: true
  individual_flags:
    - name: rust-unit-tests
      carryforward: true
    - name: rust-slow-tests
      carryforward: true
    - name: python-unit-tests
      carryforward: true
    - name: spark-tests
      carryforward: true
    - name: ibis-tests
      carryforward: true

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
