coverage:
  status:
    patch:
      default:
        target: 0
    project:
      default:
        target: 0
        informational: true

codecov:
  notify:
    after_n_builds: 1

comment:
  layout: "header, files"

ignore:
  - "crates/sail-gold-test"

flags:
  rust-unit:
    paths:
      - crates/
    carry_forward: true
  python-unit:
    paths:
      - crates/
    carry_forward: true
  spark-tests:
    paths:
      - crates/
    carry_forward: true
