codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true
    manual_trigger: true

comment:
  layout: "header, diff, flags, components, tree"
  show_carryforward_flags: true

ignore:
  - "crates/sail-gold-test"

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 20%
        informational: true

coverage:
  status:
    project:
      rust:
        flags:
          - rust-unit-tests
          - rust-slow-tests
      python:
        flags:
          - python-unit-tests
      spark:
        flags:
          - spark-tests
      ibis:
        flags:
          - ibis-tests
