codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true
    manual_trigger: true

comment:
  layout: "header, diff, flags, components, tree"
  show_carryforward_flags: true

ignore:
  - "crates/sail-gold-test"

flags:
  rust-unit-tests:
    carryforward: true
  rust-slow-tests:
    carryforward: true
  python-unit-tests:
    carryforward: true
  spark-tests:
    carryforward: true
  ibis-tests:
    carryforward: true

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
