coverage:
  status:
    patch:
      default:
        target: 0
    project:
      default:
        target: auto
        threshold: 10%
      rust_unit:
        target: auto
        flags:
          - rust-unit
      python_unit:
        target: auto
        flags:
          - python-unit
      spark_tests:
        target: auto
        flags:
          - spark-tests
      carryforward: true
      informational: true

codecov:
  notify:
    after_n_builds: 1

comment:
  layout: "header, files"

ignore:
  - "crates/sail-gold-test"

flags:
  rust-unit:
    paths:
      - crates/
  python-unit:
    paths:
      - crates/
  spark-tests:
    paths:
      - crates/
