coverage:
  status:
    patch: false
    project:
      default: false
      cargo:
        only_pulls: true
        flags:
          - cargo
        paths:
          - "crates/"
        target: auto
        threshold: 10%
        informational: true
      spark:
        only_pulls: true
        flags:
          - spark
        paths:
          - "crates/"
          - "python/"
        target: auto
        threshold: 10%
        informational: true
      python:
        only_pulls: true
        flags:
          - python
        paths:
          - "crates/"
          - "python/"
        target: auto
        threshold: 10%
        informational: true

codecov:
  notify:
    after_n_builds: 2

comment:
  layout: " diff, files"

flags:
  cargo:
    paths:
      - crates/
  spark:
    paths:
      - crates/
      - python/
  python:
    paths:
      - crates/
      - python/
