coverage:
  status:
    patch:
      default:
        target: 0
    project:
      default:
        only_pulls: true
        paths:
          - "crates/"
        target: 0
        informational: true

codecov:
  notify:
    after_n_builds: 1

comment:
  layout: "condensed_header, condensed_files"

ignore:
  - "crates/sail-gold-test"
