coverage:
  status:
    patch: false
    project:
      default: false
      cargo:
        only_pulls: true
        flags:
          - cargo
        paths:
          - "crates/"
        target: 0
        informational: true
      spark:
        only_pulls: true
        flags:
          - spark
        paths:
          - "crates/"
        target: 0
        informational: true
      python:
        only_pulls: true
        flags:
          - python
        paths:
          - "crates/"
        target: 0
        informational: true

codecov:
  notify:
    after_n_builds: 2

comment:
  layout: "diff, files"

ignore:
  - "crates/sail-gold-test"
