"""The result type of every arithmetic cell BOTH engines answer, keyed `<ansi>|<op>|<left>|<right>`.

Recorded against Spark 4.2.0 and Sail; see `test_arithmetic_matrix_types.py`, which reads this and
rewrites it one engine at a time."""

MATRIX_TYPES = {
    "false|%|bigint|bigint": {"spark": "bigint", "sail": "bigint"},
    "false|%|bigint|decimal": {"spark": "decimal(10,2)", "sail": "decimal(12,2)"},
    "false|%|bigint|double": {"spark": "double", "sail": "double"},
    "false|%|bigint|float": {"spark": "float", "sail": "float"},
    "false|%|bigint|int": {"spark": "bigint", "sail": "bigint"},
    "false|%|bigint|null": {"spark": "bigint", "sail": "bigint"},
    "false|%|bigint|smallint": {"spark": "bigint", "sail": "bigint"},
    "false|%|bigint|string": {"spark": "double", "sail": "double"},
    "false|%|bigint|tinyint": {"spark": "bigint", "sail": "bigint"},
    "false|%|decimal|bigint": {"spark": "decimal(10,2)", "sail": "decimal(10,2)"},
    "false|%|decimal|decimal": {"spark": "decimal(10,2)", "sail": "decimal(10,2)"},
    "false|%|decimal|double": {"spark": "double", "sail": "double"},
    "false|%|decimal|float": {"spark": "double", "sail": "double"},
    "false|%|decimal|int": {"spark": "decimal(10,2)", "sail": "decimal(10,2)"},
    "false|%|decimal|null": {"spark": "decimal(10,2)", "sail": "decimal(10,2)"},
    "false|%|decimal|smallint": {"spark": "decimal(7,2)", "sail": "decimal(10,2)"},
    "false|%|decimal|string": {"spark": "double", "sail": "double"},
    "false|%|decimal|tinyint": {"spark": "decimal(5,2)", "sail": "decimal(10,2)"},
    "false|%|double|bigint": {"spark": "double", "sail": "double"},
    "false|%|double|decimal": {"spark": "double", "sail": "double"},
    "false|%|double|double": {"spark": "double", "sail": "double"},
    "false|%|double|float": {"spark": "double", "sail": "double"},
    "false|%|double|int": {"spark": "double", "sail": "double"},
    "false|%|double|null": {"spark": "double", "sail": "double"},
    "false|%|double|smallint": {"spark": "double", "sail": "double"},
    "false|%|double|string": {"spark": "double", "sail": "double"},
    "false|%|double|tinyint": {"spark": "double", "sail": "double"},
    "false|%|float|bigint": {"spark": "float", "sail": "float"},
    "false|%|float|decimal": {"spark": "double", "sail": "double"},
    "false|%|float|double": {"spark": "double", "sail": "double"},
    "false|%|float|float": {"spark": "float", "sail": "float"},
    "false|%|float|int": {"spark": "float", "sail": "float"},
    "false|%|float|null": {"spark": "float", "sail": "float"},
    "false|%|float|smallint": {"spark": "float", "sail": "float"},
    "false|%|float|string": {"spark": "double", "sail": "double"},
    "false|%|float|tinyint": {"spark": "float", "sail": "float"},
    "false|%|int|bigint": {"spark": "bigint", "sail": "bigint"},
    "false|%|int|decimal": {"spark": "decimal(10,2)", "sail": "decimal(12,2)"},
    "false|%|int|double": {"spark": "double", "sail": "double"},
    "false|%|int|float": {"spark": "float", "sail": "float"},
    "false|%|int|int": {"spark": "int", "sail": "int"},
    "false|%|int|null": {"spark": "int", "sail": "int"},
    "false|%|int|smallint": {"spark": "int", "sail": "int"},
    "false|%|int|string": {"spark": "double", "sail": "double"},
    "false|%|int|tinyint": {"spark": "int", "sail": "int"},
    "false|%|null|bigint": {"spark": "bigint", "sail": "bigint"},
    "false|%|null|decimal": {"spark": "decimal(10,2)", "sail": "decimal(12,2)"},
    "false|%|null|double": {"spark": "double", "sail": "double"},
    "false|%|null|float": {"spark": "float", "sail": "float"},
    "false|%|null|int": {"spark": "int", "sail": "int"},
    "false|%|null|null": {"spark": "double", "sail": "double"},
    "false|%|null|smallint": {"spark": "smallint", "sail": "int"},
    "false|%|null|string": {"spark": "double", "sail": "double"},
    "false|%|null|tinyint": {"spark": "tinyint", "sail": "int"},
    "false|%|smallint|bigint": {"spark": "bigint", "sail": "bigint"},
    "false|%|smallint|decimal": {"spark": "decimal(7,2)", "sail": "decimal(7,2)"},
    "false|%|smallint|double": {"spark": "double", "sail": "double"},
    "false|%|smallint|float": {"spark": "float", "sail": "float"},
    "false|%|smallint|int": {"spark": "int", "sail": "int"},
    "false|%|smallint|null": {"spark": "smallint", "sail": "int"},
    "false|%|smallint|smallint": {"spark": "smallint", "sail": "smallint"},
    "false|%|smallint|string": {"spark": "double", "sail": "double"},
    "false|%|smallint|tinyint": {"spark": "smallint", "sail": "int"},
    "false|%|tinyint|bigint": {"spark": "bigint", "sail": "bigint"},
    "false|%|tinyint|decimal": {"spark": "decimal(5,2)", "sail": "decimal(5,2)"},
    "false|%|tinyint|double": {"spark": "double", "sail": "double"},
    "false|%|tinyint|float": {"spark": "float", "sail": "float"},
    "false|%|tinyint|int": {"spark": "int", "sail": "int"},
    "false|%|tinyint|null": {"spark": "tinyint", "sail": "int"},
    "false|%|tinyint|smallint": {"spark": "smallint", "sail": "int"},
    "false|%|tinyint|string": {"spark": "double", "sail": "double"},
    "false|%|tinyint|tinyint": {"spark": "tinyint", "sail": "tinyint"},
    "false|*|bigint|bigint": {"spark": "bigint", "sail": "bigint"},
    "false|*|bigint|decimal": {"spark": "decimal(31,2)", "sail": "decimal(31,2)"},
    "false|*|bigint|double": {"spark": "double", "sail": "double"},
    "false|*|bigint|float": {"spark": "float", "sail": "float"},
    "false|*|bigint|int": {"spark": "bigint", "sail": "bigint"},
    "false|*|bigint|interval_day": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|bigint|interval_dts": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|bigint|interval_hts": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|bigint|interval_ym": {"spark": "interval year to month", "sail": "interval year to month"},
    "false|*|bigint|null": {"spark": "bigint", "sail": "bigint"},
    "false|*|bigint|smallint": {"spark": "bigint", "sail": "bigint"},
    "false|*|bigint|tinyint": {"spark": "bigint", "sail": "bigint"},
    "false|*|decimal|bigint": {"spark": "decimal(31,2)", "sail": "decimal(31,2)"},
    "false|*|decimal|decimal": {"spark": "decimal(21,4)", "sail": "decimal(21,4)"},
    "false|*|decimal|double": {"spark": "double", "sail": "double"},
    "false|*|decimal|float": {"spark": "double", "sail": "double"},
    "false|*|decimal|int": {"spark": "decimal(21,2)", "sail": "decimal(21,2)"},
    "false|*|decimal|interval_day": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|decimal|interval_dts": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|decimal|interval_hts": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|decimal|interval_ym": {"spark": "interval year to month", "sail": "interval year to month"},
    "false|*|decimal|null": {"spark": "decimal(21,4)", "sail": "decimal(21,4)"},
    "false|*|decimal|smallint": {"spark": "decimal(16,2)", "sail": "decimal(16,2)"},
    "false|*|decimal|tinyint": {"spark": "decimal(14,2)", "sail": "decimal(14,2)"},
    "false|*|double|bigint": {"spark": "double", "sail": "double"},
    "false|*|double|decimal": {"spark": "double", "sail": "double"},
    "false|*|double|double": {"spark": "double", "sail": "double"},
    "false|*|double|float": {"spark": "double", "sail": "double"},
    "false|*|double|int": {"spark": "double", "sail": "double"},
    "false|*|double|interval_day": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|double|interval_dts": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|double|interval_hts": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|double|interval_ym": {"spark": "interval year to month", "sail": "interval year to month"},
    "false|*|double|null": {"spark": "double", "sail": "double"},
    "false|*|double|smallint": {"spark": "double", "sail": "double"},
    "false|*|double|tinyint": {"spark": "double", "sail": "double"},
    "false|*|float|bigint": {"spark": "float", "sail": "float"},
    "false|*|float|decimal": {"spark": "double", "sail": "double"},
    "false|*|float|double": {"spark": "double", "sail": "double"},
    "false|*|float|float": {"spark": "float", "sail": "float"},
    "false|*|float|int": {"spark": "float", "sail": "float"},
    "false|*|float|interval_day": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|float|interval_dts": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|float|interval_hts": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|float|interval_ym": {"spark": "interval year to month", "sail": "interval year to month"},
    "false|*|float|null": {"spark": "float", "sail": "float"},
    "false|*|float|smallint": {"spark": "float", "sail": "float"},
    "false|*|float|tinyint": {"spark": "float", "sail": "float"},
    "false|*|interval_day|bigint": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|interval_day|decimal": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|interval_day|double": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|interval_day|float": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|interval_day|int": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|interval_day|null": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|interval_day|smallint": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|interval_day|string": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|interval_day|tinyint": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|interval_dts|bigint": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|interval_dts|decimal": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|interval_dts|double": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|interval_dts|float": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|interval_dts|int": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|interval_dts|null": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|interval_dts|smallint": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|interval_dts|string": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|interval_dts|tinyint": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|interval_hts|bigint": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|interval_hts|decimal": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|interval_hts|double": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|interval_hts|float": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|interval_hts|int": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|interval_hts|null": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|interval_hts|smallint": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|interval_hts|string": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|interval_hts|tinyint": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|interval_ym|bigint": {"spark": "interval year to month", "sail": "interval year to month"},
    "false|*|interval_ym|decimal": {"spark": "interval year to month", "sail": "interval year to month"},
    "false|*|interval_ym|double": {"spark": "interval year to month", "sail": "interval year to month"},
    "false|*|interval_ym|float": {"spark": "interval year to month", "sail": "interval year to month"},
    "false|*|interval_ym|int": {"spark": "interval year to month", "sail": "interval year to month"},
    "false|*|interval_ym|null": {"spark": "interval year to month", "sail": "interval year to month"},
    "false|*|interval_ym|smallint": {"spark": "interval year to month", "sail": "interval year to month"},
    "false|*|interval_ym|string": {"spark": "interval year to month", "sail": "interval year to month"},
    "false|*|interval_ym|tinyint": {"spark": "interval year to month", "sail": "interval year to month"},
    "false|*|int|bigint": {"spark": "bigint", "sail": "bigint"},
    "false|*|int|decimal": {"spark": "decimal(21,2)", "sail": "decimal(21,2)"},
    "false|*|int|double": {"spark": "double", "sail": "double"},
    "false|*|int|float": {"spark": "float", "sail": "float"},
    "false|*|int|int": {"spark": "int", "sail": "int"},
    "false|*|int|interval_day": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|int|interval_dts": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|int|interval_hts": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|int|interval_ym": {"spark": "interval year to month", "sail": "interval year to month"},
    "false|*|int|null": {"spark": "int", "sail": "int"},
    "false|*|int|smallint": {"spark": "int", "sail": "int"},
    "false|*|int|tinyint": {"spark": "int", "sail": "int"},
    "false|*|null|bigint": {"spark": "bigint", "sail": "bigint"},
    "false|*|null|decimal": {"spark": "decimal(21,4)", "sail": "decimal(21,4)"},
    "false|*|null|double": {"spark": "double", "sail": "double"},
    "false|*|null|float": {"spark": "float", "sail": "float"},
    "false|*|null|int": {"spark": "int", "sail": "int"},
    "false|*|null|interval_day": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|null|interval_dts": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|null|interval_hts": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|null|interval_ym": {"spark": "interval year to month", "sail": "interval year to month"},
    "false|*|null|null": {"spark": "double", "sail": "bigint"},
    "false|*|null|smallint": {"spark": "smallint", "sail": "smallint"},
    "false|*|null|tinyint": {"spark": "tinyint", "sail": "tinyint"},
    "false|*|smallint|bigint": {"spark": "bigint", "sail": "bigint"},
    "false|*|smallint|decimal": {"spark": "decimal(16,2)", "sail": "decimal(16,2)"},
    "false|*|smallint|double": {"spark": "double", "sail": "double"},
    "false|*|smallint|float": {"spark": "float", "sail": "float"},
    "false|*|smallint|int": {"spark": "int", "sail": "int"},
    "false|*|smallint|interval_day": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|smallint|interval_dts": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|smallint|interval_hts": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|smallint|interval_ym": {"spark": "interval year to month", "sail": "interval year to month"},
    "false|*|smallint|null": {"spark": "smallint", "sail": "smallint"},
    "false|*|smallint|smallint": {"spark": "smallint", "sail": "smallint"},
    "false|*|smallint|tinyint": {"spark": "smallint", "sail": "smallint"},
    "false|*|string|interval_day": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|string|interval_dts": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|string|interval_hts": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|string|interval_ym": {"spark": "interval year to month", "sail": "interval year to month"},
    "false|*|tinyint|bigint": {"spark": "bigint", "sail": "bigint"},
    "false|*|tinyint|decimal": {"spark": "decimal(14,2)", "sail": "decimal(14,2)"},
    "false|*|tinyint|double": {"spark": "double", "sail": "double"},
    "false|*|tinyint|float": {"spark": "float", "sail": "float"},
    "false|*|tinyint|int": {"spark": "int", "sail": "int"},
    "false|*|tinyint|interval_day": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|tinyint|interval_dts": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|tinyint|interval_hts": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|*|tinyint|interval_ym": {"spark": "interval year to month", "sail": "interval year to month"},
    "false|*|tinyint|null": {"spark": "tinyint", "sail": "tinyint"},
    "false|*|tinyint|smallint": {"spark": "smallint", "sail": "smallint"},
    "false|*|tinyint|tinyint": {"spark": "tinyint", "sail": "tinyint"},
    "false|+|bigint|bigint": {"spark": "bigint", "sail": "bigint"},
    "false|+|bigint|decimal": {"spark": "decimal(23,2)", "sail": "decimal(23,2)"},
    "false|+|bigint|double": {"spark": "double", "sail": "double"},
    "false|+|bigint|float": {"spark": "float", "sail": "float"},
    "false|+|bigint|int": {"spark": "bigint", "sail": "bigint"},
    "false|+|bigint|null": {"spark": "bigint", "sail": "bigint"},
    "false|+|bigint|smallint": {"spark": "bigint", "sail": "bigint"},
    "false|+|bigint|tinyint": {"spark": "bigint", "sail": "bigint"},
    "false|+|date|int": {"spark": "date", "sail": "date"},
    "false|+|date|interval_cal": {"spark": "date", "sail": "date"},
    "false|+|date|interval_day": {"spark": "date", "sail": "date"},
    "false|+|date|interval_dts": {"spark": "timestamp", "sail": "timestamp"},
    "false|+|date|interval_hts": {"spark": "timestamp", "sail": "timestamp"},
    "false|+|date|interval_ym": {"spark": "date", "sail": "date"},
    "false|+|date|null": {"spark": "timestamp", "sail": "timestamp"},
    "false|+|date|smallint": {"spark": "date", "sail": "date"},
    "false|+|date|tinyint": {"spark": "date", "sail": "date"},
    "false|+|decimal|bigint": {"spark": "decimal(23,2)", "sail": "decimal(23,2)"},
    "false|+|decimal|decimal": {"spark": "decimal(11,2)", "sail": "decimal(11,2)"},
    "false|+|decimal|double": {"spark": "double", "sail": "double"},
    "false|+|decimal|float": {"spark": "double", "sail": "double"},
    "false|+|decimal|int": {"spark": "decimal(13,2)", "sail": "decimal(13,2)"},
    "false|+|decimal|null": {"spark": "decimal(11,2)", "sail": "decimal(11,2)"},
    "false|+|decimal|smallint": {"spark": "decimal(11,2)", "sail": "decimal(11,2)"},
    "false|+|decimal|tinyint": {"spark": "decimal(11,2)", "sail": "decimal(11,2)"},
    "false|+|double|bigint": {"spark": "double", "sail": "double"},
    "false|+|double|decimal": {"spark": "double", "sail": "double"},
    "false|+|double|double": {"spark": "double", "sail": "double"},
    "false|+|double|float": {"spark": "double", "sail": "double"},
    "false|+|double|int": {"spark": "double", "sail": "double"},
    "false|+|double|null": {"spark": "double", "sail": "double"},
    "false|+|double|smallint": {"spark": "double", "sail": "double"},
    "false|+|double|tinyint": {"spark": "double", "sail": "double"},
    "false|+|float|bigint": {"spark": "float", "sail": "float"},
    "false|+|float|decimal": {"spark": "double", "sail": "double"},
    "false|+|float|double": {"spark": "double", "sail": "double"},
    "false|+|float|float": {"spark": "float", "sail": "float"},
    "false|+|float|int": {"spark": "float", "sail": "float"},
    "false|+|float|null": {"spark": "float", "sail": "float"},
    "false|+|float|smallint": {"spark": "float", "sail": "float"},
    "false|+|float|tinyint": {"spark": "float", "sail": "float"},
    "false|+|interval_cal|date": {"spark": "date", "sail": "date"},
    "false|+|interval_cal|interval_cal": {"spark": "interval", "sail": "interval"},
    "false|+|interval_cal|null": {"spark": "interval", "sail": "interval"},
    "false|+|interval_cal|timestamp": {"spark": "timestamp", "sail": "timestamp"},
    "false|+|interval_cal|timestamp_ntz": {"spark": "timestamp_ntz", "sail": "timestamp_ntz"},
    "false|+|interval_day|date": {"spark": "date", "sail": "date"},
    "false|+|interval_day|interval_day": {"spark": "interval day", "sail": "interval day"},
    "false|+|interval_day|interval_dts": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|+|interval_day|interval_hts": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|+|interval_day|null": {"spark": "interval day", "sail": "interval day"},
    "false|+|interval_day|string": {"spark": "string", "sail": "string"},
    "false|+|interval_day|time": {"spark": "time(6)", "sail": "time(6)"},
    "false|+|interval_day|timestamp": {"spark": "timestamp", "sail": "timestamp"},
    "false|+|interval_day|timestamp_ntz": {"spark": "timestamp_ntz", "sail": "timestamp_ntz"},
    "false|+|interval_dts|date": {"spark": "timestamp", "sail": "timestamp"},
    "false|+|interval_dts|interval_day": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|+|interval_dts|interval_dts": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|+|interval_dts|interval_hts": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|+|interval_dts|null": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|+|interval_dts|string": {"spark": "string", "sail": "string"},
    "false|+|interval_dts|time": {"spark": "time(6)", "sail": "time(6)"},
    "false|+|interval_dts|timestamp": {"spark": "timestamp", "sail": "timestamp"},
    "false|+|interval_dts|timestamp_ntz": {"spark": "timestamp_ntz", "sail": "timestamp_ntz"},
    "false|+|interval_hts|date": {"spark": "timestamp", "sail": "timestamp"},
    "false|+|interval_hts|interval_day": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|+|interval_hts|interval_dts": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|+|interval_hts|interval_hts": {"spark": "interval hour to second", "sail": "interval hour to second"},
    "false|+|interval_hts|null": {"spark": "interval hour to second", "sail": "interval hour to second"},
    "false|+|interval_hts|string": {"spark": "string", "sail": "string"},
    "false|+|interval_hts|time": {"spark": "time(6)", "sail": "time(6)"},
    "false|+|interval_hts|timestamp": {"spark": "timestamp", "sail": "timestamp"},
    "false|+|interval_hts|timestamp_ntz": {"spark": "timestamp_ntz", "sail": "timestamp_ntz"},
    "false|+|interval_ym|date": {"spark": "date", "sail": "date"},
    "false|+|interval_ym|interval_ym": {"spark": "interval year", "sail": "interval year"},
    "false|+|interval_ym|null": {"spark": "interval year", "sail": "interval year"},
    "false|+|interval_ym|timestamp": {"spark": "timestamp", "sail": "timestamp"},
    "false|+|interval_ym|timestamp_ntz": {"spark": "timestamp_ntz", "sail": "timestamp_ntz"},
    "false|+|int|bigint": {"spark": "bigint", "sail": "bigint"},
    "false|+|int|date": {"spark": "date", "sail": "date"},
    "false|+|int|decimal": {"spark": "decimal(13,2)", "sail": "decimal(13,2)"},
    "false|+|int|double": {"spark": "double", "sail": "double"},
    "false|+|int|float": {"spark": "float", "sail": "float"},
    "false|+|int|int": {"spark": "int", "sail": "int"},
    "false|+|int|null": {"spark": "int", "sail": "int"},
    "false|+|int|smallint": {"spark": "int", "sail": "int"},
    "false|+|int|tinyint": {"spark": "int", "sail": "int"},
    "false|+|null|bigint": {"spark": "bigint", "sail": "bigint"},
    "false|+|null|date": {"spark": "timestamp", "sail": "timestamp"},
    "false|+|null|decimal": {"spark": "decimal(11,2)", "sail": "decimal(11,2)"},
    "false|+|null|double": {"spark": "double", "sail": "double"},
    "false|+|null|float": {"spark": "float", "sail": "float"},
    "false|+|null|int": {"spark": "int", "sail": "int"},
    "false|+|null|interval_cal": {"spark": "interval", "sail": "interval"},
    "false|+|null|interval_day": {"spark": "interval day", "sail": "interval day"},
    "false|+|null|interval_dts": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|+|null|interval_hts": {"spark": "interval hour to second", "sail": "interval hour to second"},
    "false|+|null|interval_ym": {"spark": "interval year", "sail": "interval year"},
    "false|+|null|null": {"spark": "double", "sail": "bigint"},
    "false|+|null|smallint": {"spark": "smallint", "sail": "smallint"},
    "false|+|null|time": {"spark": "time(6)", "sail": "time(6)"},
    "false|+|null|timestamp": {"spark": "timestamp", "sail": "timestamp"},
    "false|+|null|timestamp_ntz": {"spark": "timestamp_ntz", "sail": "timestamp_ntz"},
    "false|+|null|tinyint": {"spark": "tinyint", "sail": "tinyint"},
    "false|+|smallint|bigint": {"spark": "bigint", "sail": "bigint"},
    "false|+|smallint|date": {"spark": "date", "sail": "date"},
    "false|+|smallint|decimal": {"spark": "decimal(11,2)", "sail": "decimal(11,2)"},
    "false|+|smallint|double": {"spark": "double", "sail": "double"},
    "false|+|smallint|float": {"spark": "float", "sail": "float"},
    "false|+|smallint|int": {"spark": "int", "sail": "int"},
    "false|+|smallint|null": {"spark": "smallint", "sail": "smallint"},
    "false|+|smallint|smallint": {"spark": "smallint", "sail": "smallint"},
    "false|+|smallint|tinyint": {"spark": "smallint", "sail": "smallint"},
    "false|+|string|interval_day": {"spark": "string", "sail": "string"},
    "false|+|string|interval_dts": {"spark": "string", "sail": "string"},
    "false|+|string|interval_hts": {"spark": "string", "sail": "string"},
    "false|+|timestamp_ntz|interval_cal": {"spark": "timestamp_ntz", "sail": "timestamp_ntz"},
    "false|+|timestamp_ntz|interval_day": {"spark": "timestamp_ntz", "sail": "timestamp_ntz"},
    "false|+|timestamp_ntz|interval_dts": {"spark": "timestamp_ntz", "sail": "timestamp_ntz"},
    "false|+|timestamp_ntz|interval_hts": {"spark": "timestamp_ntz", "sail": "timestamp_ntz"},
    "false|+|timestamp_ntz|interval_ym": {"spark": "timestamp_ntz", "sail": "timestamp_ntz"},
    "false|+|timestamp_ntz|null": {"spark": "timestamp_ntz", "sail": "timestamp_ntz"},
    "false|+|timestamp|interval_cal": {"spark": "timestamp", "sail": "timestamp"},
    "false|+|timestamp|interval_day": {"spark": "timestamp", "sail": "timestamp"},
    "false|+|timestamp|interval_dts": {"spark": "timestamp", "sail": "timestamp"},
    "false|+|timestamp|interval_hts": {"spark": "timestamp", "sail": "timestamp"},
    "false|+|timestamp|interval_ym": {"spark": "timestamp", "sail": "timestamp"},
    "false|+|timestamp|null": {"spark": "timestamp", "sail": "timestamp"},
    "false|+|time|interval_day": {"spark": "time(6)", "sail": "time(6)"},
    "false|+|time|interval_dts": {"spark": "time(6)", "sail": "time(6)"},
    "false|+|time|interval_hts": {"spark": "time(6)", "sail": "time(6)"},
    "false|+|time|null": {"spark": "time(6)", "sail": "time(6)"},
    "false|+|tinyint|bigint": {"spark": "bigint", "sail": "bigint"},
    "false|+|tinyint|date": {"spark": "date", "sail": "date"},
    "false|+|tinyint|decimal": {"spark": "decimal(11,2)", "sail": "decimal(11,2)"},
    "false|+|tinyint|double": {"spark": "double", "sail": "double"},
    "false|+|tinyint|float": {"spark": "float", "sail": "float"},
    "false|+|tinyint|int": {"spark": "int", "sail": "int"},
    "false|+|tinyint|null": {"spark": "tinyint", "sail": "tinyint"},
    "false|+|tinyint|smallint": {"spark": "smallint", "sail": "smallint"},
    "false|+|tinyint|tinyint": {"spark": "tinyint", "sail": "tinyint"},
    "false|-|bigint|bigint": {"spark": "bigint", "sail": "bigint"},
    "false|-|bigint|decimal": {"spark": "decimal(23,2)", "sail": "decimal(23,2)"},
    "false|-|bigint|double": {"spark": "double", "sail": "double"},
    "false|-|bigint|float": {"spark": "float", "sail": "float"},
    "false|-|bigint|int": {"spark": "bigint", "sail": "bigint"},
    "false|-|bigint|null": {"spark": "bigint", "sail": "bigint"},
    "false|-|bigint|smallint": {"spark": "bigint", "sail": "bigint"},
    "false|-|bigint|tinyint": {"spark": "bigint", "sail": "bigint"},
    "false|-|date|date": {"spark": "interval day", "sail": "interval day"},
    "false|-|date|int": {"spark": "date", "sail": "date"},
    "false|-|date|interval_cal": {"spark": "date", "sail": "date"},
    "false|-|date|interval_day": {"spark": "date", "sail": "date"},
    "false|-|date|interval_dts": {"spark": "timestamp", "sail": "timestamp"},
    "false|-|date|interval_hts": {"spark": "timestamp", "sail": "timestamp"},
    "false|-|date|interval_ym": {"spark": "date", "sail": "date"},
    "false|-|date|null": {"spark": "interval day", "sail": "interval day"},
    "false|-|date|smallint": {"spark": "date", "sail": "date"},
    "false|-|date|timestamp": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|-|date|timestamp_ntz": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|-|date|tinyint": {"spark": "date", "sail": "date"},
    "false|-|decimal|bigint": {"spark": "decimal(23,2)", "sail": "decimal(23,2)"},
    "false|-|decimal|decimal": {"spark": "decimal(11,2)", "sail": "decimal(11,2)"},
    "false|-|decimal|double": {"spark": "double", "sail": "double"},
    "false|-|decimal|float": {"spark": "double", "sail": "double"},
    "false|-|decimal|int": {"spark": "decimal(13,2)", "sail": "decimal(13,2)"},
    "false|-|decimal|null": {"spark": "decimal(11,2)", "sail": "decimal(11,2)"},
    "false|-|decimal|smallint": {"spark": "decimal(11,2)", "sail": "decimal(11,2)"},
    "false|-|decimal|tinyint": {"spark": "decimal(11,2)", "sail": "decimal(11,2)"},
    "false|-|double|bigint": {"spark": "double", "sail": "double"},
    "false|-|double|decimal": {"spark": "double", "sail": "double"},
    "false|-|double|double": {"spark": "double", "sail": "double"},
    "false|-|double|float": {"spark": "double", "sail": "double"},
    "false|-|double|int": {"spark": "double", "sail": "double"},
    "false|-|double|null": {"spark": "double", "sail": "double"},
    "false|-|double|smallint": {"spark": "double", "sail": "double"},
    "false|-|double|tinyint": {"spark": "double", "sail": "double"},
    "false|-|float|bigint": {"spark": "float", "sail": "float"},
    "false|-|float|decimal": {"spark": "double", "sail": "double"},
    "false|-|float|double": {"spark": "double", "sail": "double"},
    "false|-|float|float": {"spark": "float", "sail": "float"},
    "false|-|float|int": {"spark": "float", "sail": "float"},
    "false|-|float|null": {"spark": "float", "sail": "float"},
    "false|-|float|smallint": {"spark": "float", "sail": "float"},
    "false|-|float|tinyint": {"spark": "float", "sail": "float"},
    "false|-|interval_cal|interval_cal": {"spark": "interval", "sail": "interval"},
    "false|-|interval_cal|null": {"spark": "interval", "sail": "interval"},
    "false|-|interval_day|interval_day": {"spark": "interval day", "sail": "interval day"},
    "false|-|interval_day|interval_dts": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|-|interval_day|interval_hts": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|-|interval_day|null": {"spark": "interval day", "sail": "interval day"},
    "false|-|interval_dts|interval_day": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|-|interval_dts|interval_dts": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|-|interval_dts|interval_hts": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|-|interval_dts|null": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|-|interval_hts|interval_day": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|-|interval_hts|interval_dts": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|-|interval_hts|interval_hts": {"spark": "interval hour to second", "sail": "interval hour to second"},
    "false|-|interval_hts|null": {"spark": "interval hour to second", "sail": "interval hour to second"},
    "false|-|interval_ym|interval_ym": {"spark": "interval year", "sail": "interval year"},
    "false|-|interval_ym|null": {"spark": "interval year", "sail": "interval year"},
    "false|-|int|bigint": {"spark": "bigint", "sail": "bigint"},
    "false|-|int|decimal": {"spark": "decimal(13,2)", "sail": "decimal(13,2)"},
    "false|-|int|double": {"spark": "double", "sail": "double"},
    "false|-|int|float": {"spark": "float", "sail": "float"},
    "false|-|int|int": {"spark": "int", "sail": "int"},
    "false|-|int|null": {"spark": "int", "sail": "int"},
    "false|-|int|smallint": {"spark": "int", "sail": "int"},
    "false|-|int|tinyint": {"spark": "int", "sail": "int"},
    "false|-|null|bigint": {"spark": "bigint", "sail": "bigint"},
    "false|-|null|date": {"spark": "interval day", "sail": "interval day"},
    "false|-|null|decimal": {"spark": "decimal(11,2)", "sail": "decimal(11,2)"},
    "false|-|null|double": {"spark": "double", "sail": "double"},
    "false|-|null|float": {"spark": "float", "sail": "float"},
    "false|-|null|int": {"spark": "int", "sail": "int"},
    "false|-|null|interval_cal": {"spark": "interval", "sail": "interval"},
    "false|-|null|interval_day": {"spark": "interval day", "sail": "interval day"},
    "false|-|null|interval_dts": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|-|null|interval_hts": {"spark": "interval hour to second", "sail": "interval hour to second"},
    "false|-|null|interval_ym": {"spark": "interval year", "sail": "interval year"},
    "false|-|null|null": {"spark": "double", "sail": "bigint"},
    "false|-|null|smallint": {"spark": "smallint", "sail": "smallint"},
    "false|-|null|time": {"spark": "interval hour to second", "sail": "interval hour to second"},
    "false|-|null|timestamp": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|-|null|timestamp_ntz": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|-|null|tinyint": {"spark": "tinyint", "sail": "tinyint"},
    "false|-|smallint|bigint": {"spark": "bigint", "sail": "bigint"},
    "false|-|smallint|decimal": {"spark": "decimal(11,2)", "sail": "decimal(11,2)"},
    "false|-|smallint|double": {"spark": "double", "sail": "double"},
    "false|-|smallint|float": {"spark": "float", "sail": "float"},
    "false|-|smallint|int": {"spark": "int", "sail": "int"},
    "false|-|smallint|null": {"spark": "smallint", "sail": "smallint"},
    "false|-|smallint|smallint": {"spark": "smallint", "sail": "smallint"},
    "false|-|smallint|tinyint": {"spark": "smallint", "sail": "smallint"},
    "false|-|timestamp_ntz|date": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|-|timestamp_ntz|interval_cal": {"spark": "timestamp_ntz", "sail": "timestamp_ntz"},
    "false|-|timestamp_ntz|interval_day": {"spark": "timestamp_ntz", "sail": "timestamp_ntz"},
    "false|-|timestamp_ntz|interval_dts": {"spark": "timestamp_ntz", "sail": "timestamp_ntz"},
    "false|-|timestamp_ntz|interval_hts": {"spark": "timestamp_ntz", "sail": "timestamp_ntz"},
    "false|-|timestamp_ntz|interval_ym": {"spark": "timestamp_ntz", "sail": "timestamp_ntz"},
    "false|-|timestamp_ntz|null": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|-|timestamp_ntz|timestamp": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|-|timestamp_ntz|timestamp_ntz": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|-|timestamp|date": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|-|timestamp|interval_cal": {"spark": "timestamp", "sail": "timestamp"},
    "false|-|timestamp|interval_day": {"spark": "timestamp", "sail": "timestamp"},
    "false|-|timestamp|interval_dts": {"spark": "timestamp", "sail": "timestamp"},
    "false|-|timestamp|interval_hts": {"spark": "timestamp", "sail": "timestamp"},
    "false|-|timestamp|interval_ym": {"spark": "timestamp", "sail": "timestamp"},
    "false|-|timestamp|null": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|-|timestamp|timestamp": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|-|timestamp|timestamp_ntz": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|-|time|interval_day": {"spark": "time(6)", "sail": "time(6)"},
    "false|-|time|interval_dts": {"spark": "time(6)", "sail": "time(6)"},
    "false|-|time|interval_hts": {"spark": "time(6)", "sail": "time(6)"},
    "false|-|time|null": {"spark": "interval hour to second", "sail": "interval hour to second"},
    "false|-|time|time": {"spark": "interval hour to second", "sail": "interval hour to second"},
    "false|-|tinyint|bigint": {"spark": "bigint", "sail": "bigint"},
    "false|-|tinyint|decimal": {"spark": "decimal(11,2)", "sail": "decimal(11,2)"},
    "false|-|tinyint|double": {"spark": "double", "sail": "double"},
    "false|-|tinyint|float": {"spark": "float", "sail": "float"},
    "false|-|tinyint|int": {"spark": "int", "sail": "int"},
    "false|-|tinyint|null": {"spark": "tinyint", "sail": "tinyint"},
    "false|-|tinyint|smallint": {"spark": "smallint", "sail": "smallint"},
    "false|-|tinyint|tinyint": {"spark": "tinyint", "sail": "tinyint"},
    "false|/|bigint|bigint": {"spark": "double", "sail": "double"},
    "false|/|bigint|decimal": {"spark": "decimal(33,11)", "sail": "decimal(33,11)"},
    "false|/|bigint|double": {"spark": "double", "sail": "double"},
    "false|/|bigint|float": {"spark": "double", "sail": "double"},
    "false|/|bigint|int": {"spark": "double", "sail": "double"},
    "false|/|bigint|null": {"spark": "double", "sail": "double"},
    "false|/|bigint|smallint": {"spark": "double", "sail": "double"},
    "false|/|bigint|string": {"spark": "double", "sail": "double"},
    "false|/|bigint|tinyint": {"spark": "double", "sail": "double"},
    "false|/|decimal|bigint": {"spark": "decimal(31,23)", "sail": "decimal(31,23)"},
    "false|/|decimal|decimal": {"spark": "decimal(23,13)", "sail": "decimal(23,13)"},
    "false|/|decimal|double": {"spark": "double", "sail": "double"},
    "false|/|decimal|float": {"spark": "double", "sail": "double"},
    "false|/|decimal|int": {"spark": "decimal(21,13)", "sail": "decimal(21,13)"},
    "false|/|decimal|null": {"spark": "decimal(23,13)", "sail": "decimal(14,6)"},
    "false|/|decimal|smallint": {"spark": "decimal(16,8)", "sail": "decimal(16,8)"},
    "false|/|decimal|string": {"spark": "double", "sail": "double"},
    "false|/|decimal|tinyint": {"spark": "decimal(14,6)", "sail": "decimal(14,6)"},
    "false|/|double|bigint": {"spark": "double", "sail": "double"},
    "false|/|double|decimal": {"spark": "double", "sail": "double"},
    "false|/|double|double": {"spark": "double", "sail": "double"},
    "false|/|double|float": {"spark": "double", "sail": "double"},
    "false|/|double|int": {"spark": "double", "sail": "double"},
    "false|/|double|null": {"spark": "double", "sail": "double"},
    "false|/|double|smallint": {"spark": "double", "sail": "double"},
    "false|/|double|string": {"spark": "double", "sail": "double"},
    "false|/|double|tinyint": {"spark": "double", "sail": "double"},
    "false|/|float|bigint": {"spark": "double", "sail": "double"},
    "false|/|float|decimal": {"spark": "double", "sail": "double"},
    "false|/|float|double": {"spark": "double", "sail": "double"},
    "false|/|float|float": {"spark": "double", "sail": "double"},
    "false|/|float|int": {"spark": "double", "sail": "double"},
    "false|/|float|null": {"spark": "double", "sail": "double"},
    "false|/|float|smallint": {"spark": "double", "sail": "double"},
    "false|/|float|string": {"spark": "double", "sail": "double"},
    "false|/|float|tinyint": {"spark": "double", "sail": "double"},
    "false|/|interval_cal|bigint": {"spark": "interval", "sail": "interval"},
    "false|/|interval_cal|double": {"spark": "interval", "sail": "interval"},
    "false|/|interval_cal|float": {"spark": "interval", "sail": "interval"},
    "false|/|interval_cal|int": {"spark": "interval", "sail": "interval"},
    "false|/|interval_cal|null": {"spark": "interval", "sail": "interval"},
    "false|/|interval_cal|smallint": {"spark": "interval", "sail": "interval"},
    "false|/|interval_cal|string": {"spark": "interval", "sail": "interval"},
    "false|/|interval_cal|tinyint": {"spark": "interval", "sail": "interval"},
    "false|/|interval_day|bigint": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|/|interval_day|decimal": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|/|interval_day|double": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|/|interval_day|float": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|/|interval_day|int": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|/|interval_day|null": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|/|interval_day|smallint": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|/|interval_day|string": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|/|interval_day|tinyint": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|/|interval_dts|bigint": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|/|interval_dts|decimal": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|/|interval_dts|double": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|/|interval_dts|float": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|/|interval_dts|int": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|/|interval_dts|null": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|/|interval_dts|smallint": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|/|interval_dts|string": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|/|interval_dts|tinyint": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|/|interval_hts|bigint": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|/|interval_hts|decimal": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|/|interval_hts|double": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|/|interval_hts|float": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|/|interval_hts|int": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|/|interval_hts|null": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|/|interval_hts|smallint": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|/|interval_hts|string": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|/|interval_hts|tinyint": {"spark": "interval day to second", "sail": "interval day to second"},
    "false|/|interval_ym|bigint": {"spark": "interval year to month", "sail": "interval year to month"},
    "false|/|interval_ym|decimal": {"spark": "interval year to month", "sail": "interval year to month"},
    "false|/|interval_ym|double": {"spark": "interval year to month", "sail": "interval year to month"},
    "false|/|interval_ym|float": {"spark": "interval year to month", "sail": "interval year to month"},
    "false|/|interval_ym|int": {"spark": "interval year to month", "sail": "interval year to month"},
    "false|/|interval_ym|null": {"spark": "interval year to month", "sail": "interval year to month"},
    "false|/|interval_ym|smallint": {"spark": "interval year to month", "sail": "interval year to month"},
    "false|/|interval_ym|string": {"spark": "interval year to month", "sail": "interval year to month"},
    "false|/|interval_ym|tinyint": {"spark": "interval year to month", "sail": "interval year to month"},
    "false|/|int|bigint": {"spark": "double", "sail": "double"},
    "false|/|int|decimal": {"spark": "decimal(23,11)", "sail": "decimal(23,11)"},
    "false|/|int|double": {"spark": "double", "sail": "double"},
    "false|/|int|float": {"spark": "double", "sail": "double"},
    "false|/|int|int": {"spark": "double", "sail": "double"},
    "false|/|int|null": {"spark": "double", "sail": "double"},
    "false|/|int|smallint": {"spark": "double", "sail": "double"},
    "false|/|int|string": {"spark": "double", "sail": "double"},
    "false|/|int|tinyint": {"spark": "double", "sail": "double"},
    "false|/|null|bigint": {"spark": "double", "sail": "double"},
    "false|/|null|decimal": {"spark": "double", "sail": "decimal(18,6)"},
    "false|/|null|double": {"spark": "double", "sail": "double"},
    "false|/|null|float": {"spark": "double", "sail": "double"},
    "false|/|null|int": {"spark": "double", "sail": "double"},
    "false|/|null|null": {"spark": "double", "sail": "double"},
    "false|/|null|smallint": {"spark": "double", "sail": "double"},
    "false|/|null|string": {"spark": "double", "sail": "double"},
    "false|/|null|tinyint": {"spark": "double", "sail": "double"},
    "false|/|smallint|bigint": {"spark": "double", "sail": "double"},
    "false|/|smallint|decimal": {"spark": "decimal(18,11)", "sail": "decimal(18,11)"},
    "false|/|smallint|double": {"spark": "double", "sail": "double"},
    "false|/|smallint|float": {"spark": "double", "sail": "double"},
    "false|/|smallint|int": {"spark": "double", "sail": "double"},
    "false|/|smallint|null": {"spark": "double", "sail": "double"},
    "false|/|smallint|smallint": {"spark": "double", "sail": "double"},
    "false|/|smallint|string": {"spark": "double", "sail": "double"},
    "false|/|smallint|tinyint": {"spark": "double", "sail": "double"},
    "false|/|string|bigint": {"spark": "double", "sail": "double"},
    "false|/|string|double": {"spark": "double", "sail": "double"},
    "false|/|string|float": {"spark": "double", "sail": "double"},
    "false|/|string|int": {"spark": "double", "sail": "double"},
    "false|/|string|null": {"spark": "double", "sail": "double"},
    "false|/|string|smallint": {"spark": "double", "sail": "double"},
    "false|/|string|string": {"spark": "double", "sail": "double"},
    "false|/|string|tinyint": {"spark": "double", "sail": "double"},
    "false|/|tinyint|bigint": {"spark": "double", "sail": "double"},
    "false|/|tinyint|decimal": {"spark": "decimal(16,11)", "sail": "decimal(16,11)"},
    "false|/|tinyint|double": {"spark": "double", "sail": "double"},
    "false|/|tinyint|float": {"spark": "double", "sail": "double"},
    "false|/|tinyint|int": {"spark": "double", "sail": "double"},
    "false|/|tinyint|null": {"spark": "double", "sail": "double"},
    "false|/|tinyint|smallint": {"spark": "double", "sail": "double"},
    "false|/|tinyint|string": {"spark": "double", "sail": "double"},
    "false|/|tinyint|tinyint": {"spark": "double", "sail": "double"},
    "true|%|bigint|bigint": {"spark": "bigint", "sail": "bigint"},
    "true|%|bigint|decimal": {"spark": "decimal(10,2)", "sail": "decimal(10,2)"},
    "true|%|bigint|double": {"spark": "double", "sail": "double"},
    "true|%|bigint|float": {"spark": "double", "sail": "float"},
    "true|%|bigint|int": {"spark": "bigint", "sail": "bigint"},
    "true|%|bigint|null": {"spark": "bigint", "sail": "bigint"},
    "true|%|bigint|smallint": {"spark": "bigint", "sail": "bigint"},
    "true|%|bigint|tinyint": {"spark": "bigint", "sail": "bigint"},
    "true|%|decimal|bigint": {"spark": "decimal(10,2)", "sail": "decimal(10,2)"},
    "true|%|decimal|decimal": {"spark": "decimal(10,2)", "sail": "decimal(10,2)"},
    "true|%|decimal|double": {"spark": "double", "sail": "double"},
    "true|%|decimal|float": {"spark": "double", "sail": "double"},
    "true|%|decimal|int": {"spark": "decimal(10,2)", "sail": "decimal(10,2)"},
    "true|%|decimal|null": {"spark": "decimal(10,2)", "sail": "decimal(10,2)"},
    "true|%|decimal|smallint": {"spark": "decimal(7,2)", "sail": "decimal(7,2)"},
    "true|%|decimal|tinyint": {"spark": "decimal(5,2)", "sail": "decimal(5,2)"},
    "true|%|double|bigint": {"spark": "double", "sail": "double"},
    "true|%|double|decimal": {"spark": "double", "sail": "double"},
    "true|%|double|double": {"spark": "double", "sail": "double"},
    "true|%|double|float": {"spark": "double", "sail": "double"},
    "true|%|double|int": {"spark": "double", "sail": "double"},
    "true|%|double|null": {"spark": "double", "sail": "double"},
    "true|%|double|smallint": {"spark": "double", "sail": "double"},
    "true|%|double|tinyint": {"spark": "double", "sail": "double"},
    "true|%|float|bigint": {"spark": "double", "sail": "float"},
    "true|%|float|decimal": {"spark": "double", "sail": "double"},
    "true|%|float|double": {"spark": "double", "sail": "double"},
    "true|%|float|float": {"spark": "float", "sail": "float"},
    "true|%|float|int": {"spark": "double", "sail": "float"},
    "true|%|float|null": {"spark": "float", "sail": "float"},
    "true|%|float|smallint": {"spark": "double", "sail": "float"},
    "true|%|float|tinyint": {"spark": "double", "sail": "float"},
    "true|%|int|bigint": {"spark": "bigint", "sail": "bigint"},
    "true|%|int|decimal": {"spark": "decimal(10,2)", "sail": "decimal(10,2)"},
    "true|%|int|double": {"spark": "double", "sail": "double"},
    "true|%|int|float": {"spark": "double", "sail": "float"},
    "true|%|int|int": {"spark": "int", "sail": "int"},
    "true|%|int|null": {"spark": "int", "sail": "int"},
    "true|%|int|smallint": {"spark": "int", "sail": "int"},
    "true|%|int|tinyint": {"spark": "int", "sail": "int"},
    "true|%|null|bigint": {"spark": "bigint", "sail": "bigint"},
    "true|%|null|decimal": {"spark": "decimal(10,2)", "sail": "decimal(10,2)"},
    "true|%|null|double": {"spark": "double", "sail": "double"},
    "true|%|null|float": {"spark": "float", "sail": "float"},
    "true|%|null|int": {"spark": "int", "sail": "int"},
    "true|%|null|null": {"spark": "double", "sail": "double"},
    "true|%|null|smallint": {"spark": "smallint", "sail": "smallint"},
    "true|%|null|tinyint": {"spark": "tinyint", "sail": "tinyint"},
    "true|%|smallint|bigint": {"spark": "bigint", "sail": "bigint"},
    "true|%|smallint|decimal": {"spark": "decimal(7,2)", "sail": "decimal(7,2)"},
    "true|%|smallint|double": {"spark": "double", "sail": "double"},
    "true|%|smallint|float": {"spark": "double", "sail": "float"},
    "true|%|smallint|int": {"spark": "int", "sail": "int"},
    "true|%|smallint|null": {"spark": "smallint", "sail": "smallint"},
    "true|%|smallint|smallint": {"spark": "smallint", "sail": "smallint"},
    "true|%|smallint|tinyint": {"spark": "smallint", "sail": "smallint"},
    "true|%|tinyint|bigint": {"spark": "bigint", "sail": "bigint"},
    "true|%|tinyint|decimal": {"spark": "decimal(5,2)", "sail": "decimal(5,2)"},
    "true|%|tinyint|double": {"spark": "double", "sail": "double"},
    "true|%|tinyint|float": {"spark": "double", "sail": "float"},
    "true|%|tinyint|int": {"spark": "int", "sail": "int"},
    "true|%|tinyint|null": {"spark": "tinyint", "sail": "tinyint"},
    "true|%|tinyint|smallint": {"spark": "smallint", "sail": "smallint"},
    "true|%|tinyint|tinyint": {"spark": "tinyint", "sail": "tinyint"},
    "true|*|bigint|bigint": {"spark": "bigint", "sail": "bigint"},
    "true|*|bigint|decimal": {"spark": "decimal(31,2)", "sail": "decimal(31,2)"},
    "true|*|bigint|double": {"spark": "double", "sail": "double"},
    "true|*|bigint|float": {"spark": "double", "sail": "float"},
    "true|*|bigint|int": {"spark": "bigint", "sail": "bigint"},
    "true|*|bigint|interval_day": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|bigint|interval_dts": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|bigint|interval_hts": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|bigint|interval_ym": {"spark": "interval year to month", "sail": "interval year to month"},
    "true|*|bigint|null": {"spark": "bigint", "sail": "bigint"},
    "true|*|bigint|smallint": {"spark": "bigint", "sail": "bigint"},
    "true|*|bigint|tinyint": {"spark": "bigint", "sail": "bigint"},
    "true|*|decimal|bigint": {"spark": "decimal(31,2)", "sail": "decimal(31,2)"},
    "true|*|decimal|decimal": {"spark": "decimal(21,4)", "sail": "decimal(21,4)"},
    "true|*|decimal|double": {"spark": "double", "sail": "double"},
    "true|*|decimal|float": {"spark": "double", "sail": "double"},
    "true|*|decimal|int": {"spark": "decimal(21,2)", "sail": "decimal(21,2)"},
    "true|*|decimal|interval_day": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|decimal|interval_dts": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|decimal|interval_hts": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|decimal|interval_ym": {"spark": "interval year to month", "sail": "interval year to month"},
    "true|*|decimal|null": {"spark": "decimal(21,4)", "sail": "decimal(21,4)"},
    "true|*|decimal|smallint": {"spark": "decimal(16,2)", "sail": "decimal(16,2)"},
    "true|*|decimal|tinyint": {"spark": "decimal(14,2)", "sail": "decimal(14,2)"},
    "true|*|double|bigint": {"spark": "double", "sail": "double"},
    "true|*|double|decimal": {"spark": "double", "sail": "double"},
    "true|*|double|double": {"spark": "double", "sail": "double"},
    "true|*|double|float": {"spark": "double", "sail": "double"},
    "true|*|double|int": {"spark": "double", "sail": "double"},
    "true|*|double|interval_day": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|double|interval_dts": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|double|interval_hts": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|double|interval_ym": {"spark": "interval year to month", "sail": "interval year to month"},
    "true|*|double|null": {"spark": "double", "sail": "double"},
    "true|*|double|smallint": {"spark": "double", "sail": "double"},
    "true|*|double|tinyint": {"spark": "double", "sail": "double"},
    "true|*|float|bigint": {"spark": "double", "sail": "float"},
    "true|*|float|decimal": {"spark": "double", "sail": "double"},
    "true|*|float|double": {"spark": "double", "sail": "double"},
    "true|*|float|float": {"spark": "float", "sail": "float"},
    "true|*|float|int": {"spark": "double", "sail": "float"},
    "true|*|float|interval_day": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|float|interval_dts": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|float|interval_hts": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|float|interval_ym": {"spark": "interval year to month", "sail": "interval year to month"},
    "true|*|float|null": {"spark": "float", "sail": "float"},
    "true|*|float|smallint": {"spark": "double", "sail": "float"},
    "true|*|float|tinyint": {"spark": "double", "sail": "float"},
    "true|*|interval_day|bigint": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|interval_day|decimal": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|interval_day|double": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|interval_day|float": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|interval_day|int": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|interval_day|null": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|interval_day|smallint": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|interval_day|string": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|interval_day|tinyint": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|interval_dts|bigint": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|interval_dts|decimal": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|interval_dts|double": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|interval_dts|float": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|interval_dts|int": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|interval_dts|null": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|interval_dts|smallint": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|interval_dts|string": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|interval_dts|tinyint": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|interval_hts|bigint": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|interval_hts|decimal": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|interval_hts|double": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|interval_hts|float": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|interval_hts|int": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|interval_hts|null": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|interval_hts|smallint": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|interval_hts|string": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|interval_hts|tinyint": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|interval_ym|bigint": {"spark": "interval year to month", "sail": "interval year to month"},
    "true|*|interval_ym|decimal": {"spark": "interval year to month", "sail": "interval year to month"},
    "true|*|interval_ym|double": {"spark": "interval year to month", "sail": "interval year to month"},
    "true|*|interval_ym|float": {"spark": "interval year to month", "sail": "interval year to month"},
    "true|*|interval_ym|int": {"spark": "interval year to month", "sail": "interval year to month"},
    "true|*|interval_ym|null": {"spark": "interval year to month", "sail": "interval year to month"},
    "true|*|interval_ym|smallint": {"spark": "interval year to month", "sail": "interval year to month"},
    "true|*|interval_ym|string": {"spark": "interval year to month", "sail": "interval year to month"},
    "true|*|interval_ym|tinyint": {"spark": "interval year to month", "sail": "interval year to month"},
    "true|*|int|bigint": {"spark": "bigint", "sail": "bigint"},
    "true|*|int|decimal": {"spark": "decimal(21,2)", "sail": "decimal(21,2)"},
    "true|*|int|double": {"spark": "double", "sail": "double"},
    "true|*|int|float": {"spark": "double", "sail": "float"},
    "true|*|int|int": {"spark": "int", "sail": "int"},
    "true|*|int|interval_day": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|int|interval_dts": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|int|interval_hts": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|int|interval_ym": {"spark": "interval year to month", "sail": "interval year to month"},
    "true|*|int|null": {"spark": "int", "sail": "int"},
    "true|*|int|smallint": {"spark": "int", "sail": "int"},
    "true|*|int|tinyint": {"spark": "int", "sail": "int"},
    "true|*|null|bigint": {"spark": "bigint", "sail": "bigint"},
    "true|*|null|decimal": {"spark": "decimal(21,4)", "sail": "decimal(21,4)"},
    "true|*|null|double": {"spark": "double", "sail": "double"},
    "true|*|null|float": {"spark": "float", "sail": "float"},
    "true|*|null|int": {"spark": "int", "sail": "int"},
    "true|*|null|interval_day": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|null|interval_dts": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|null|interval_hts": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|null|interval_ym": {"spark": "interval year to month", "sail": "interval year to month"},
    "true|*|null|null": {"spark": "double", "sail": "bigint"},
    "true|*|null|smallint": {"spark": "smallint", "sail": "smallint"},
    "true|*|null|tinyint": {"spark": "tinyint", "sail": "tinyint"},
    "true|*|smallint|bigint": {"spark": "bigint", "sail": "bigint"},
    "true|*|smallint|decimal": {"spark": "decimal(16,2)", "sail": "decimal(16,2)"},
    "true|*|smallint|double": {"spark": "double", "sail": "double"},
    "true|*|smallint|float": {"spark": "double", "sail": "float"},
    "true|*|smallint|int": {"spark": "int", "sail": "int"},
    "true|*|smallint|interval_day": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|smallint|interval_dts": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|smallint|interval_hts": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|smallint|interval_ym": {"spark": "interval year to month", "sail": "interval year to month"},
    "true|*|smallint|null": {"spark": "smallint", "sail": "smallint"},
    "true|*|smallint|smallint": {"spark": "smallint", "sail": "smallint"},
    "true|*|smallint|tinyint": {"spark": "smallint", "sail": "smallint"},
    "true|*|string|interval_day": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|string|interval_dts": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|string|interval_hts": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|string|interval_ym": {"spark": "interval year to month", "sail": "interval year to month"},
    "true|*|tinyint|bigint": {"spark": "bigint", "sail": "bigint"},
    "true|*|tinyint|decimal": {"spark": "decimal(14,2)", "sail": "decimal(14,2)"},
    "true|*|tinyint|double": {"spark": "double", "sail": "double"},
    "true|*|tinyint|float": {"spark": "double", "sail": "float"},
    "true|*|tinyint|int": {"spark": "int", "sail": "int"},
    "true|*|tinyint|interval_day": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|tinyint|interval_dts": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|tinyint|interval_hts": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|*|tinyint|interval_ym": {"spark": "interval year to month", "sail": "interval year to month"},
    "true|*|tinyint|null": {"spark": "tinyint", "sail": "tinyint"},
    "true|*|tinyint|smallint": {"spark": "smallint", "sail": "smallint"},
    "true|*|tinyint|tinyint": {"spark": "tinyint", "sail": "tinyint"},
    "true|+|bigint|bigint": {"spark": "bigint", "sail": "bigint"},
    "true|+|bigint|decimal": {"spark": "decimal(23,2)", "sail": "decimal(23,2)"},
    "true|+|bigint|double": {"spark": "double", "sail": "double"},
    "true|+|bigint|float": {"spark": "double", "sail": "float"},
    "true|+|bigint|int": {"spark": "bigint", "sail": "bigint"},
    "true|+|bigint|null": {"spark": "bigint", "sail": "bigint"},
    "true|+|bigint|smallint": {"spark": "bigint", "sail": "bigint"},
    "true|+|bigint|tinyint": {"spark": "bigint", "sail": "bigint"},
    "true|+|date|int": {"spark": "date", "sail": "date"},
    "true|+|date|interval_cal": {"spark": "date", "sail": "date"},
    "true|+|date|interval_day": {"spark": "date", "sail": "date"},
    "true|+|date|interval_dts": {"spark": "timestamp", "sail": "timestamp"},
    "true|+|date|interval_hts": {"spark": "timestamp", "sail": "timestamp"},
    "true|+|date|interval_ym": {"spark": "date", "sail": "date"},
    "true|+|date|null": {"spark": "timestamp", "sail": "timestamp"},
    "true|+|date|smallint": {"spark": "date", "sail": "date"},
    "true|+|date|tinyint": {"spark": "date", "sail": "date"},
    "true|+|decimal|bigint": {"spark": "decimal(23,2)", "sail": "decimal(23,2)"},
    "true|+|decimal|decimal": {"spark": "decimal(11,2)", "sail": "decimal(11,2)"},
    "true|+|decimal|double": {"spark": "double", "sail": "double"},
    "true|+|decimal|float": {"spark": "double", "sail": "double"},
    "true|+|decimal|int": {"spark": "decimal(13,2)", "sail": "decimal(13,2)"},
    "true|+|decimal|null": {"spark": "decimal(11,2)", "sail": "decimal(11,2)"},
    "true|+|decimal|smallint": {"spark": "decimal(11,2)", "sail": "decimal(11,2)"},
    "true|+|decimal|tinyint": {"spark": "decimal(11,2)", "sail": "decimal(11,2)"},
    "true|+|double|bigint": {"spark": "double", "sail": "double"},
    "true|+|double|decimal": {"spark": "double", "sail": "double"},
    "true|+|double|double": {"spark": "double", "sail": "double"},
    "true|+|double|float": {"spark": "double", "sail": "double"},
    "true|+|double|int": {"spark": "double", "sail": "double"},
    "true|+|double|null": {"spark": "double", "sail": "double"},
    "true|+|double|smallint": {"spark": "double", "sail": "double"},
    "true|+|double|tinyint": {"spark": "double", "sail": "double"},
    "true|+|float|bigint": {"spark": "double", "sail": "float"},
    "true|+|float|decimal": {"spark": "double", "sail": "double"},
    "true|+|float|double": {"spark": "double", "sail": "double"},
    "true|+|float|float": {"spark": "float", "sail": "float"},
    "true|+|float|int": {"spark": "double", "sail": "float"},
    "true|+|float|null": {"spark": "float", "sail": "float"},
    "true|+|float|smallint": {"spark": "double", "sail": "float"},
    "true|+|float|tinyint": {"spark": "double", "sail": "float"},
    "true|+|interval_cal|date": {"spark": "date", "sail": "date"},
    "true|+|interval_cal|interval_cal": {"spark": "interval", "sail": "interval"},
    "true|+|interval_cal|null": {"spark": "interval", "sail": "interval"},
    "true|+|interval_cal|timestamp": {"spark": "timestamp", "sail": "timestamp"},
    "true|+|interval_cal|timestamp_ntz": {"spark": "timestamp_ntz", "sail": "timestamp_ntz"},
    "true|+|interval_day|date": {"spark": "date", "sail": "date"},
    "true|+|interval_day|interval_day": {"spark": "interval day", "sail": "interval day"},
    "true|+|interval_day|interval_dts": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|+|interval_day|interval_hts": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|+|interval_day|null": {"spark": "interval day", "sail": "interval day"},
    "true|+|interval_day|string": {"spark": "string", "sail": "string"},
    "true|+|interval_day|time": {"spark": "time(6)", "sail": "time(6)"},
    "true|+|interval_day|timestamp": {"spark": "timestamp", "sail": "timestamp"},
    "true|+|interval_day|timestamp_ntz": {"spark": "timestamp_ntz", "sail": "timestamp_ntz"},
    "true|+|interval_dts|date": {"spark": "timestamp", "sail": "timestamp"},
    "true|+|interval_dts|interval_day": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|+|interval_dts|interval_dts": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|+|interval_dts|interval_hts": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|+|interval_dts|null": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|+|interval_dts|string": {"spark": "string", "sail": "string"},
    "true|+|interval_dts|time": {"spark": "time(6)", "sail": "time(6)"},
    "true|+|interval_dts|timestamp": {"spark": "timestamp", "sail": "timestamp"},
    "true|+|interval_dts|timestamp_ntz": {"spark": "timestamp_ntz", "sail": "timestamp_ntz"},
    "true|+|interval_hts|date": {"spark": "timestamp", "sail": "timestamp"},
    "true|+|interval_hts|interval_day": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|+|interval_hts|interval_dts": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|+|interval_hts|interval_hts": {"spark": "interval hour to second", "sail": "interval hour to second"},
    "true|+|interval_hts|null": {"spark": "interval hour to second", "sail": "interval hour to second"},
    "true|+|interval_hts|string": {"spark": "string", "sail": "string"},
    "true|+|interval_hts|time": {"spark": "time(6)", "sail": "time(6)"},
    "true|+|interval_hts|timestamp": {"spark": "timestamp", "sail": "timestamp"},
    "true|+|interval_hts|timestamp_ntz": {"spark": "timestamp_ntz", "sail": "timestamp_ntz"},
    "true|+|interval_ym|date": {"spark": "date", "sail": "date"},
    "true|+|interval_ym|interval_ym": {"spark": "interval year", "sail": "interval year"},
    "true|+|interval_ym|null": {"spark": "interval year", "sail": "interval year"},
    "true|+|interval_ym|timestamp": {"spark": "timestamp", "sail": "timestamp"},
    "true|+|interval_ym|timestamp_ntz": {"spark": "timestamp_ntz", "sail": "timestamp_ntz"},
    "true|+|int|bigint": {"spark": "bigint", "sail": "bigint"},
    "true|+|int|date": {"spark": "date", "sail": "date"},
    "true|+|int|decimal": {"spark": "decimal(13,2)", "sail": "decimal(13,2)"},
    "true|+|int|double": {"spark": "double", "sail": "double"},
    "true|+|int|float": {"spark": "double", "sail": "float"},
    "true|+|int|int": {"spark": "int", "sail": "int"},
    "true|+|int|null": {"spark": "int", "sail": "int"},
    "true|+|int|smallint": {"spark": "int", "sail": "int"},
    "true|+|int|tinyint": {"spark": "int", "sail": "int"},
    "true|+|null|bigint": {"spark": "bigint", "sail": "bigint"},
    "true|+|null|date": {"spark": "timestamp", "sail": "timestamp"},
    "true|+|null|decimal": {"spark": "decimal(11,2)", "sail": "decimal(11,2)"},
    "true|+|null|double": {"spark": "double", "sail": "double"},
    "true|+|null|float": {"spark": "float", "sail": "float"},
    "true|+|null|int": {"spark": "int", "sail": "int"},
    "true|+|null|interval_cal": {"spark": "interval", "sail": "interval"},
    "true|+|null|interval_day": {"spark": "interval day", "sail": "interval day"},
    "true|+|null|interval_dts": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|+|null|interval_hts": {"spark": "interval hour to second", "sail": "interval hour to second"},
    "true|+|null|interval_ym": {"spark": "interval year", "sail": "interval year"},
    "true|+|null|null": {"spark": "double", "sail": "bigint"},
    "true|+|null|smallint": {"spark": "smallint", "sail": "smallint"},
    "true|+|null|time": {"spark": "time(6)", "sail": "time(6)"},
    "true|+|null|timestamp": {"spark": "timestamp", "sail": "timestamp"},
    "true|+|null|timestamp_ntz": {"spark": "timestamp_ntz", "sail": "timestamp_ntz"},
    "true|+|null|tinyint": {"spark": "tinyint", "sail": "tinyint"},
    "true|+|smallint|bigint": {"spark": "bigint", "sail": "bigint"},
    "true|+|smallint|date": {"spark": "date", "sail": "date"},
    "true|+|smallint|decimal": {"spark": "decimal(11,2)", "sail": "decimal(11,2)"},
    "true|+|smallint|double": {"spark": "double", "sail": "double"},
    "true|+|smallint|float": {"spark": "double", "sail": "float"},
    "true|+|smallint|int": {"spark": "int", "sail": "int"},
    "true|+|smallint|null": {"spark": "smallint", "sail": "smallint"},
    "true|+|smallint|smallint": {"spark": "smallint", "sail": "smallint"},
    "true|+|smallint|tinyint": {"spark": "smallint", "sail": "smallint"},
    "true|+|string|interval_day": {"spark": "string", "sail": "string"},
    "true|+|string|interval_dts": {"spark": "string", "sail": "string"},
    "true|+|string|interval_hts": {"spark": "string", "sail": "string"},
    "true|+|timestamp_ntz|interval_cal": {"spark": "timestamp_ntz", "sail": "timestamp_ntz"},
    "true|+|timestamp_ntz|interval_day": {"spark": "timestamp_ntz", "sail": "timestamp_ntz"},
    "true|+|timestamp_ntz|interval_dts": {"spark": "timestamp_ntz", "sail": "timestamp_ntz"},
    "true|+|timestamp_ntz|interval_hts": {"spark": "timestamp_ntz", "sail": "timestamp_ntz"},
    "true|+|timestamp_ntz|interval_ym": {"spark": "timestamp_ntz", "sail": "timestamp_ntz"},
    "true|+|timestamp_ntz|null": {"spark": "timestamp_ntz", "sail": "timestamp_ntz"},
    "true|+|timestamp|interval_cal": {"spark": "timestamp", "sail": "timestamp"},
    "true|+|timestamp|interval_day": {"spark": "timestamp", "sail": "timestamp"},
    "true|+|timestamp|interval_dts": {"spark": "timestamp", "sail": "timestamp"},
    "true|+|timestamp|interval_hts": {"spark": "timestamp", "sail": "timestamp"},
    "true|+|timestamp|interval_ym": {"spark": "timestamp", "sail": "timestamp"},
    "true|+|timestamp|null": {"spark": "timestamp", "sail": "timestamp"},
    "true|+|time|interval_day": {"spark": "time(6)", "sail": "time(6)"},
    "true|+|time|interval_dts": {"spark": "time(6)", "sail": "time(6)"},
    "true|+|time|interval_hts": {"spark": "time(6)", "sail": "time(6)"},
    "true|+|time|null": {"spark": "time(6)", "sail": "time(6)"},
    "true|+|tinyint|bigint": {"spark": "bigint", "sail": "bigint"},
    "true|+|tinyint|date": {"spark": "date", "sail": "date"},
    "true|+|tinyint|decimal": {"spark": "decimal(11,2)", "sail": "decimal(11,2)"},
    "true|+|tinyint|double": {"spark": "double", "sail": "double"},
    "true|+|tinyint|float": {"spark": "double", "sail": "float"},
    "true|+|tinyint|int": {"spark": "int", "sail": "int"},
    "true|+|tinyint|null": {"spark": "tinyint", "sail": "tinyint"},
    "true|+|tinyint|smallint": {"spark": "smallint", "sail": "smallint"},
    "true|+|tinyint|tinyint": {"spark": "tinyint", "sail": "tinyint"},
    "true|-|bigint|bigint": {"spark": "bigint", "sail": "bigint"},
    "true|-|bigint|decimal": {"spark": "decimal(23,2)", "sail": "decimal(23,2)"},
    "true|-|bigint|double": {"spark": "double", "sail": "double"},
    "true|-|bigint|float": {"spark": "double", "sail": "float"},
    "true|-|bigint|int": {"spark": "bigint", "sail": "bigint"},
    "true|-|bigint|null": {"spark": "bigint", "sail": "bigint"},
    "true|-|bigint|smallint": {"spark": "bigint", "sail": "bigint"},
    "true|-|bigint|tinyint": {"spark": "bigint", "sail": "bigint"},
    "true|-|date|date": {"spark": "interval day", "sail": "interval day"},
    "true|-|date|int": {"spark": "date", "sail": "date"},
    "true|-|date|interval_cal": {"spark": "date", "sail": "date"},
    "true|-|date|interval_day": {"spark": "date", "sail": "date"},
    "true|-|date|interval_dts": {"spark": "timestamp", "sail": "timestamp"},
    "true|-|date|interval_hts": {"spark": "timestamp", "sail": "timestamp"},
    "true|-|date|interval_ym": {"spark": "date", "sail": "date"},
    "true|-|date|null": {"spark": "interval day", "sail": "interval day"},
    "true|-|date|smallint": {"spark": "date", "sail": "date"},
    "true|-|date|timestamp": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|-|date|timestamp_ntz": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|-|date|tinyint": {"spark": "date", "sail": "date"},
    "true|-|decimal|bigint": {"spark": "decimal(23,2)", "sail": "decimal(23,2)"},
    "true|-|decimal|decimal": {"spark": "decimal(11,2)", "sail": "decimal(11,2)"},
    "true|-|decimal|double": {"spark": "double", "sail": "double"},
    "true|-|decimal|float": {"spark": "double", "sail": "double"},
    "true|-|decimal|int": {"spark": "decimal(13,2)", "sail": "decimal(13,2)"},
    "true|-|decimal|null": {"spark": "decimal(11,2)", "sail": "decimal(11,2)"},
    "true|-|decimal|smallint": {"spark": "decimal(11,2)", "sail": "decimal(11,2)"},
    "true|-|decimal|tinyint": {"spark": "decimal(11,2)", "sail": "decimal(11,2)"},
    "true|-|double|bigint": {"spark": "double", "sail": "double"},
    "true|-|double|decimal": {"spark": "double", "sail": "double"},
    "true|-|double|double": {"spark": "double", "sail": "double"},
    "true|-|double|float": {"spark": "double", "sail": "double"},
    "true|-|double|int": {"spark": "double", "sail": "double"},
    "true|-|double|null": {"spark": "double", "sail": "double"},
    "true|-|double|smallint": {"spark": "double", "sail": "double"},
    "true|-|double|tinyint": {"spark": "double", "sail": "double"},
    "true|-|float|bigint": {"spark": "double", "sail": "float"},
    "true|-|float|decimal": {"spark": "double", "sail": "double"},
    "true|-|float|double": {"spark": "double", "sail": "double"},
    "true|-|float|float": {"spark": "float", "sail": "float"},
    "true|-|float|int": {"spark": "double", "sail": "float"},
    "true|-|float|null": {"spark": "float", "sail": "float"},
    "true|-|float|smallint": {"spark": "double", "sail": "float"},
    "true|-|float|tinyint": {"spark": "double", "sail": "float"},
    "true|-|interval_cal|interval_cal": {"spark": "interval", "sail": "interval"},
    "true|-|interval_cal|null": {"spark": "interval", "sail": "interval"},
    "true|-|interval_day|interval_day": {"spark": "interval day", "sail": "interval day"},
    "true|-|interval_day|interval_dts": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|-|interval_day|interval_hts": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|-|interval_day|null": {"spark": "interval day", "sail": "interval day"},
    "true|-|interval_dts|interval_day": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|-|interval_dts|interval_dts": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|-|interval_dts|interval_hts": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|-|interval_dts|null": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|-|interval_hts|interval_day": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|-|interval_hts|interval_dts": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|-|interval_hts|interval_hts": {"spark": "interval hour to second", "sail": "interval hour to second"},
    "true|-|interval_hts|null": {"spark": "interval hour to second", "sail": "interval hour to second"},
    "true|-|interval_ym|interval_ym": {"spark": "interval year", "sail": "interval year"},
    "true|-|interval_ym|null": {"spark": "interval year", "sail": "interval year"},
    "true|-|int|bigint": {"spark": "bigint", "sail": "bigint"},
    "true|-|int|decimal": {"spark": "decimal(13,2)", "sail": "decimal(13,2)"},
    "true|-|int|double": {"spark": "double", "sail": "double"},
    "true|-|int|float": {"spark": "double", "sail": "float"},
    "true|-|int|int": {"spark": "int", "sail": "int"},
    "true|-|int|null": {"spark": "int", "sail": "int"},
    "true|-|int|smallint": {"spark": "int", "sail": "int"},
    "true|-|int|tinyint": {"spark": "int", "sail": "int"},
    "true|-|null|bigint": {"spark": "bigint", "sail": "bigint"},
    "true|-|null|date": {"spark": "interval day", "sail": "interval day"},
    "true|-|null|decimal": {"spark": "decimal(11,2)", "sail": "decimal(11,2)"},
    "true|-|null|double": {"spark": "double", "sail": "double"},
    "true|-|null|float": {"spark": "float", "sail": "float"},
    "true|-|null|int": {"spark": "int", "sail": "int"},
    "true|-|null|interval_cal": {"spark": "interval", "sail": "interval"},
    "true|-|null|interval_day": {"spark": "interval day", "sail": "interval day"},
    "true|-|null|interval_dts": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|-|null|interval_hts": {"spark": "interval hour to second", "sail": "interval hour to second"},
    "true|-|null|interval_ym": {"spark": "interval year", "sail": "interval year"},
    "true|-|null|null": {"spark": "double", "sail": "bigint"},
    "true|-|null|smallint": {"spark": "smallint", "sail": "smallint"},
    "true|-|null|time": {"spark": "interval hour to second", "sail": "interval hour to second"},
    "true|-|null|timestamp": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|-|null|timestamp_ntz": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|-|null|tinyint": {"spark": "tinyint", "sail": "tinyint"},
    "true|-|smallint|bigint": {"spark": "bigint", "sail": "bigint"},
    "true|-|smallint|decimal": {"spark": "decimal(11,2)", "sail": "decimal(11,2)"},
    "true|-|smallint|double": {"spark": "double", "sail": "double"},
    "true|-|smallint|float": {"spark": "double", "sail": "float"},
    "true|-|smallint|int": {"spark": "int", "sail": "int"},
    "true|-|smallint|null": {"spark": "smallint", "sail": "smallint"},
    "true|-|smallint|smallint": {"spark": "smallint", "sail": "smallint"},
    "true|-|smallint|tinyint": {"spark": "smallint", "sail": "smallint"},
    "true|-|timestamp_ntz|date": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|-|timestamp_ntz|interval_cal": {"spark": "timestamp_ntz", "sail": "timestamp_ntz"},
    "true|-|timestamp_ntz|interval_day": {"spark": "timestamp_ntz", "sail": "timestamp_ntz"},
    "true|-|timestamp_ntz|interval_dts": {"spark": "timestamp_ntz", "sail": "timestamp_ntz"},
    "true|-|timestamp_ntz|interval_hts": {"spark": "timestamp_ntz", "sail": "timestamp_ntz"},
    "true|-|timestamp_ntz|interval_ym": {"spark": "timestamp_ntz", "sail": "timestamp_ntz"},
    "true|-|timestamp_ntz|null": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|-|timestamp_ntz|timestamp": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|-|timestamp_ntz|timestamp_ntz": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|-|timestamp|date": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|-|timestamp|interval_cal": {"spark": "timestamp", "sail": "timestamp"},
    "true|-|timestamp|interval_day": {"spark": "timestamp", "sail": "timestamp"},
    "true|-|timestamp|interval_dts": {"spark": "timestamp", "sail": "timestamp"},
    "true|-|timestamp|interval_hts": {"spark": "timestamp", "sail": "timestamp"},
    "true|-|timestamp|interval_ym": {"spark": "timestamp", "sail": "timestamp"},
    "true|-|timestamp|null": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|-|timestamp|timestamp": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|-|timestamp|timestamp_ntz": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|-|time|interval_day": {"spark": "time(6)", "sail": "time(6)"},
    "true|-|time|interval_dts": {"spark": "time(6)", "sail": "time(6)"},
    "true|-|time|interval_hts": {"spark": "time(6)", "sail": "time(6)"},
    "true|-|time|null": {"spark": "interval hour to second", "sail": "interval hour to second"},
    "true|-|time|time": {"spark": "interval hour to second", "sail": "interval hour to second"},
    "true|-|tinyint|bigint": {"spark": "bigint", "sail": "bigint"},
    "true|-|tinyint|decimal": {"spark": "decimal(11,2)", "sail": "decimal(11,2)"},
    "true|-|tinyint|double": {"spark": "double", "sail": "double"},
    "true|-|tinyint|float": {"spark": "double", "sail": "float"},
    "true|-|tinyint|int": {"spark": "int", "sail": "int"},
    "true|-|tinyint|null": {"spark": "tinyint", "sail": "tinyint"},
    "true|-|tinyint|smallint": {"spark": "smallint", "sail": "smallint"},
    "true|-|tinyint|tinyint": {"spark": "tinyint", "sail": "tinyint"},
    "true|/|bigint|bigint": {"spark": "double", "sail": "double"},
    "true|/|bigint|decimal": {"spark": "decimal(33,11)", "sail": "decimal(33,11)"},
    "true|/|bigint|double": {"spark": "double", "sail": "double"},
    "true|/|bigint|float": {"spark": "double", "sail": "double"},
    "true|/|bigint|int": {"spark": "double", "sail": "double"},
    "true|/|bigint|null": {"spark": "double", "sail": "double"},
    "true|/|bigint|smallint": {"spark": "double", "sail": "double"},
    "true|/|bigint|string": {"spark": "double", "sail": "double"},
    "true|/|bigint|tinyint": {"spark": "double", "sail": "double"},
    "true|/|decimal|bigint": {"spark": "decimal(31,23)", "sail": "decimal(31,23)"},
    "true|/|decimal|decimal": {"spark": "decimal(23,13)", "sail": "decimal(23,13)"},
    "true|/|decimal|double": {"spark": "double", "sail": "double"},
    "true|/|decimal|float": {"spark": "double", "sail": "double"},
    "true|/|decimal|int": {"spark": "decimal(21,13)", "sail": "decimal(21,13)"},
    "true|/|decimal|null": {"spark": "decimal(23,13)", "sail": "decimal(16,6)"},
    "true|/|decimal|smallint": {"spark": "decimal(16,8)", "sail": "decimal(16,8)"},
    "true|/|decimal|tinyint": {"spark": "decimal(14,6)", "sail": "decimal(14,6)"},
    "true|/|double|bigint": {"spark": "double", "sail": "double"},
    "true|/|double|decimal": {"spark": "double", "sail": "double"},
    "true|/|double|double": {"spark": "double", "sail": "double"},
    "true|/|double|float": {"spark": "double", "sail": "double"},
    "true|/|double|int": {"spark": "double", "sail": "double"},
    "true|/|double|null": {"spark": "double", "sail": "double"},
    "true|/|double|smallint": {"spark": "double", "sail": "double"},
    "true|/|double|string": {"spark": "double", "sail": "double"},
    "true|/|double|tinyint": {"spark": "double", "sail": "double"},
    "true|/|float|bigint": {"spark": "double", "sail": "double"},
    "true|/|float|decimal": {"spark": "double", "sail": "double"},
    "true|/|float|double": {"spark": "double", "sail": "double"},
    "true|/|float|float": {"spark": "double", "sail": "double"},
    "true|/|float|int": {"spark": "double", "sail": "double"},
    "true|/|float|null": {"spark": "double", "sail": "double"},
    "true|/|float|smallint": {"spark": "double", "sail": "double"},
    "true|/|float|string": {"spark": "double", "sail": "double"},
    "true|/|float|tinyint": {"spark": "double", "sail": "double"},
    "true|/|interval_cal|bigint": {"spark": "interval", "sail": "interval"},
    "true|/|interval_cal|double": {"spark": "interval", "sail": "interval"},
    "true|/|interval_cal|float": {"spark": "interval", "sail": "interval"},
    "true|/|interval_cal|int": {"spark": "interval", "sail": "interval"},
    "true|/|interval_cal|null": {"spark": "interval", "sail": "interval"},
    "true|/|interval_cal|smallint": {"spark": "interval", "sail": "interval"},
    "true|/|interval_cal|string": {"spark": "interval", "sail": "interval"},
    "true|/|interval_cal|tinyint": {"spark": "interval", "sail": "interval"},
    "true|/|interval_day|bigint": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|/|interval_day|decimal": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|/|interval_day|double": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|/|interval_day|float": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|/|interval_day|int": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|/|interval_day|null": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|/|interval_day|smallint": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|/|interval_day|string": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|/|interval_day|tinyint": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|/|interval_dts|bigint": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|/|interval_dts|decimal": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|/|interval_dts|double": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|/|interval_dts|float": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|/|interval_dts|int": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|/|interval_dts|null": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|/|interval_dts|smallint": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|/|interval_dts|string": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|/|interval_dts|tinyint": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|/|interval_hts|bigint": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|/|interval_hts|decimal": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|/|interval_hts|double": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|/|interval_hts|float": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|/|interval_hts|int": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|/|interval_hts|null": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|/|interval_hts|smallint": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|/|interval_hts|string": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|/|interval_hts|tinyint": {"spark": "interval day to second", "sail": "interval day to second"},
    "true|/|interval_ym|bigint": {"spark": "interval year to month", "sail": "interval year to month"},
    "true|/|interval_ym|decimal": {"spark": "interval year to month", "sail": "interval year to month"},
    "true|/|interval_ym|double": {"spark": "interval year to month", "sail": "interval year to month"},
    "true|/|interval_ym|float": {"spark": "interval year to month", "sail": "interval year to month"},
    "true|/|interval_ym|int": {"spark": "interval year to month", "sail": "interval year to month"},
    "true|/|interval_ym|null": {"spark": "interval year to month", "sail": "interval year to month"},
    "true|/|interval_ym|smallint": {"spark": "interval year to month", "sail": "interval year to month"},
    "true|/|interval_ym|string": {"spark": "interval year to month", "sail": "interval year to month"},
    "true|/|interval_ym|tinyint": {"spark": "interval year to month", "sail": "interval year to month"},
    "true|/|int|bigint": {"spark": "double", "sail": "double"},
    "true|/|int|decimal": {"spark": "decimal(23,11)", "sail": "decimal(23,11)"},
    "true|/|int|double": {"spark": "double", "sail": "double"},
    "true|/|int|float": {"spark": "double", "sail": "double"},
    "true|/|int|int": {"spark": "double", "sail": "double"},
    "true|/|int|null": {"spark": "double", "sail": "double"},
    "true|/|int|smallint": {"spark": "double", "sail": "double"},
    "true|/|int|string": {"spark": "double", "sail": "double"},
    "true|/|int|tinyint": {"spark": "double", "sail": "double"},
    "true|/|null|bigint": {"spark": "double", "sail": "double"},
    "true|/|null|decimal": {"spark": "double", "sail": "decimal(16,6)"},
    "true|/|null|double": {"spark": "double", "sail": "double"},
    "true|/|null|float": {"spark": "double", "sail": "double"},
    "true|/|null|int": {"spark": "double", "sail": "double"},
    "true|/|null|null": {"spark": "double", "sail": "double"},
    "true|/|null|smallint": {"spark": "double", "sail": "double"},
    "true|/|null|tinyint": {"spark": "double", "sail": "double"},
    "true|/|smallint|bigint": {"spark": "double", "sail": "double"},
    "true|/|smallint|decimal": {"spark": "decimal(18,11)", "sail": "decimal(18,11)"},
    "true|/|smallint|double": {"spark": "double", "sail": "double"},
    "true|/|smallint|float": {"spark": "double", "sail": "double"},
    "true|/|smallint|int": {"spark": "double", "sail": "double"},
    "true|/|smallint|null": {"spark": "double", "sail": "double"},
    "true|/|smallint|smallint": {"spark": "double", "sail": "double"},
    "true|/|smallint|string": {"spark": "double", "sail": "double"},
    "true|/|smallint|tinyint": {"spark": "double", "sail": "double"},
    "true|/|string|bigint": {"spark": "double", "sail": "double"},
    "true|/|string|double": {"spark": "double", "sail": "double"},
    "true|/|string|float": {"spark": "double", "sail": "double"},
    "true|/|string|int": {"spark": "double", "sail": "double"},
    "true|/|string|smallint": {"spark": "double", "sail": "double"},
    "true|/|string|tinyint": {"spark": "double", "sail": "double"},
    "true|/|tinyint|bigint": {"spark": "double", "sail": "double"},
    "true|/|tinyint|decimal": {"spark": "decimal(16,11)", "sail": "decimal(16,11)"},
    "true|/|tinyint|double": {"spark": "double", "sail": "double"},
    "true|/|tinyint|float": {"spark": "double", "sail": "double"},
    "true|/|tinyint|int": {"spark": "double", "sail": "double"},
    "true|/|tinyint|null": {"spark": "double", "sail": "double"},
    "true|/|tinyint|smallint": {"spark": "double", "sail": "double"},
    "true|/|tinyint|string": {"spark": "double", "sail": "double"},
    "true|/|tinyint|tinyint": {"spark": "double", "sail": "double"},
}
