Feature: Delta Lake Identity Columns

  Rule: Generated always identity columns are generated by Sail

    Background:
      Given variable location for temporary directory identity_always
      Given variable delta_log for delta log of location
      Given final statement
        """
        DROP TABLE IF EXISTS delta_identity_always
        """

    @sail-only
    Scenario: Generated always identity values are assigned when omitted
      Given statement template
        """
        CREATE TABLE delta_identity_always (
          id BIGINT GENERATED ALWAYS AS IDENTITY,
          value INT
        )
        USING DELTA
        LOCATION {{ location.sql }}
        """
      Given statement
        """
        INSERT INTO delta_identity_always (value) VALUES (10), (20)
        """
      Given statement
        """
        INSERT INTO delta_identity_always (value) VALUES (30)
        """
      When query
        """
        SELECT id, value FROM delta_identity_always ORDER BY id
        """
      Then query result ordered
        | id | value |
        | 1  | 10    |
        | 2  | 20    |
        | 3  | 30    |
      Then delta log first commit protocol and metadata contains
        | path                                                                  | value               |
        | protocol.minWriterVersion                                             | 7                   |
        | protocol.writerFeatures                                               | ["identityColumns"] |
        | metaData.schemaString.fields[0].metadata["delta.identity.start"]      | 1                   |
        | metaData.schemaString.fields[0].metadata["delta.identity.step"]       | 1                   |
        | metaData.schemaString.fields[0].metadata["delta.identity.highWaterMark"] | 2                 |
        | metaData.schemaString.fields[0].metadata["delta.identity.allowExplicitInsert"] | false       |
      Then delta log latest effective protocol and metadata contains
        | path                                                                  | value |
        | metaData.schemaString.fields[0].metadata["delta.identity.highWaterMark"] | 3   |

    @sail-only
    Scenario: Generated always identity values can be omitted by position
      Given statement template
        """
        CREATE TABLE delta_identity_always (
          id BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 10 INCREMENT BY 5),
          value INT
        )
        USING DELTA
        LOCATION {{ location.sql }}
        """
      Given statement
        """
        INSERT INTO delta_identity_always VALUES (100), (200)
        """
      When query
        """
        SELECT id, value FROM delta_identity_always ORDER BY id
        """
      Then query result ordered
        | id | value |
        | 10 | 100   |
        | 15 | 200   |

    @sail-only
    Scenario: Generated always identity columns reject explicit values
      Given statement template
        """
        CREATE TABLE delta_identity_always (
          id BIGINT GENERATED ALWAYS AS IDENTITY,
          value INT
        )
        USING DELTA
        LOCATION {{ location.sql }}
        """
      When query
        """
        INSERT INTO delta_identity_always (id, value) VALUES (1, 10)
        """
      Then query error (?s).*GENERATED ALWAYS AS IDENTITY.*

  Rule: Generated by default identity columns allow explicit values

    Background:
      Given variable location for temporary directory identity_by_default
      Given final statement
        """
        DROP TABLE IF EXISTS delta_identity_by_default
        """

    @sail-only
    Scenario: Generated by default identity advances after explicit values
      Given statement template
        """
        CREATE TABLE delta_identity_by_default (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10 INCREMENT BY 3),
          value INT
        )
        USING DELTA
        LOCATION {{ location.sql }}
        """
      Given statement
        """
        INSERT INTO delta_identity_by_default (id, value) VALUES (42, 100)
        """
      Given statement
        """
        INSERT INTO delta_identity_by_default (value) VALUES (200)
        """
      When query
        """
        SELECT id, value FROM delta_identity_by_default ORDER BY value
        """
      Then query result ordered
        | id | value |
        | 42 | 100   |
        | 46 | 200   |
      Then delta log latest effective protocol and metadata contains
        | path                                                                  | value |
        | metaData.schemaString.fields[0].metadata["delta.identity.highWaterMark"] | 46  |
        | metaData.schemaString.fields[0].metadata["delta.identity.allowExplicitInsert"] | true |

    @sail-only
    Scenario: Negative identity step generates decreasing values
      Given statement template
        """
        CREATE TABLE delta_identity_by_default (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 0 INCREMENT BY -2),
          value INT
        )
        USING DELTA
        LOCATION {{ location.sql }}
        """
      Given statement
        """
        INSERT INTO delta_identity_by_default (value) VALUES (1), (2), (3)
        """
      When query
        """
        SELECT id, value FROM delta_identity_by_default ORDER BY value
        """
      Then query result ordered
        | id | value |
        | 0  | 1     |
        | -2 | 2     |
        | -4 | 3     |

  Rule: Identity column definitions are validated

    Background:
      Given variable location for temporary directory identity_invalid
      Given final statement
        """
        DROP TABLE IF EXISTS delta_identity_invalid
        """

    @sail-only
    Scenario: Identity columns must be BIGINT
      When query template
        """
        CREATE TABLE delta_identity_invalid (
          id INT GENERATED ALWAYS AS IDENTITY,
          value INT
        )
        USING DELTA
        LOCATION {{ location.sql }}
        """
      Then query error (?s).*identity column `id` must be BIGINT.*

    @sail-only
    Scenario: Identity increment cannot be zero
      When query template
        """
        CREATE TABLE delta_identity_invalid (
          id BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 0),
          value INT
        )
        USING DELTA
        LOCATION {{ location.sql }}
        """
      Then query error (?s).*INCREMENT BY value for identity column cannot be 0.*

    @sail-only
    Scenario: Identity columns cannot be partition columns
      When query template
        """
        CREATE TABLE delta_identity_invalid (
          id BIGINT GENERATED ALWAYS AS IDENTITY,
          value INT
        )
        USING DELTA
        LOCATION {{ location.sql }}
        PARTITIONED BY (id)
        """
      Then query error (?s).*PARTITIONED BY IDENTITY column `id` is not supported.*
