[package]
name = "sail-logical-optimizer"
version = { workspace = true }
edition = { workspace = true }

[lints]
workspace = true

[dependencies]
sail-function = { path = "../sail-function" }
sail-logical-plan = { path = "../sail-logical-plan" }
sail-python-udf = { path = "../sail-python-udf" }

datafusion = { workspace = true }
datafusion-common = { workspace = true }
datafusion-expr = { workspace = true }
