apiVersion: v1
kind: Service
metadata:
  name: {{ include "lakesail.fullname" . }}
  labels:
    {{- include "lakesail.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.framework.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.opentelemetryGrpc.port }}
      targetPort: otel-grpc
      protocol: TCP
      name: otel-grpc
    - port: {{ .Values.service.opentelemetryHttp.port }}
      targetPort: otel-http
      protocol: TCP
      name: otel-http
  selector:
    {{- include "lakesail.selectorLabels" . | nindent 4 }}
