[package]
name = "sail-sql-analyzer"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
sail-common = { path = "../sail-common" }
sail-sql-parser = { path = "../sail-sql-parser" }

thiserror = { workspace = true }
regex = { workspace = true }
lazy_static = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
chumsky = { workspace = true }
either = { workspace = true }
