if $group == "" then
    [
        inputs
        | select(.kind == "function")
    ]
    | map(.data.group) | unique | .[] | sub("_funcs$"; "")
else
    {
        "tests": [
            inputs
            | select(.kind == "function")
            | select(.data.group == "\($group)_funcs")
            | .data.examples[]
            | {
                "input": {
                    "query": .sql,
                    "result": .result,
                    "schema": (.schema | del(.fields[].metadata["__autoGeneratedAlias"]))
                }
            }
        ] | unique
    }
end
