import pytest

from pysail.testing.spark.utils.common import is_jvm_spark, pyspark_version

# What `fillna`, `na.fill` with a map, `na.replace` and `dropna` do with one subset name, over
# frames where the name can resolve in different ways. Spark resolves a subset name as a column
# reference (`Dataset.resolve`) before any operation decides what to do with it, so the leading
# part can be a qualifier, a key a join hid is still reachable through its qualifier, a field of a
# NULL base is NULL, and the same column selected twice is one attribute. Then each operation takes
# its own branch of `DataFrameNaFunctions`: `fill(value, subset)` keeps the attributes and drops a
# nested name, `fill(valueMap)` and `replace` refuse a nested name, and `dropna` uses any name as a
# key. Every expected value was measured on the Spark JVM; an error is compared by its class.

# Every frame has a column `a` holding the value under test and a column `b` holding 2.
_FRAMES = {
    "plain": lambda s, v: s.sql(f"SELECT {v} AS a, 2 AS b"),
    "alias": lambda s, v: s.sql(f"SELECT {v} AS a, 2 AS b").alias("t"),
    "shadow": lambda s, v: s.sql(f"SELECT named_struct('a', {v}) AS t, {v} AS a, 2 AS b").alias("t"),
    "struct": lambda s, v: s.sql(
        f"SELECT named_struct('a', {v}, 'inner', named_struct('x', {v})) AS s, {v} AS a, 2 AS b"
    ).alias("t"),
    "join": lambda s, v: s.sql(f"SELECT 1 AS id, {v} AS a, 2 AS b")
    .alias("l")
    .join(s.sql(f"SELECT 1 AS id, {v} AS a").alias("r"), "id"),
    "twice": lambda s, v: s.sql(f"SELECT {v} AS a, 2 AS b").select("a", "a", "b"),
    "nullbase": lambda s, v: s.sql(f"SELECT NULL AS n, {v} AS a, 2 AS b").alias("t"),
}
_OPERATIONS = {
    "fill": lambda df, n: df.fillna(9, subset=[n]),
    "fillmap": lambda df, n: df.na.fill({n: 9, "b": 8}),
    "replace": lambda df, n: df.na.replace(1, 7, subset=[n]),
    "dropna": lambda df, n: df.dropna(subset=[n]),
}
# Spark checks that a value of a map can be cast to the column it fills and refuses a struct; Sail
# leaves that column alone instead. This is the check on the type of the value, not on its name.
_SAIL_BUGS = {("fillmap", "struct", "t.s")}


def _plain(value):
    # A row nested in a row is a tuple too, so the result does not depend on how `Row` prints.
    return tuple(_plain(x) for x in value) if isinstance(value, tuple) else value


def _outcome(spark, operation, frame, name):
    value = "1" if operation == "replace" else "CAST(NULL AS INT)"
    try:
        rows = _OPERATIONS[operation](_FRAMES[frame](spark, value), name).collect()
    except Exception as e:  # noqa: BLE001
        text = str(e)
        start = text.find("[")
        return "ERR " + text[start + 1 : text.find("]", start)]
    return repr([_plain(row) for row in rows])


_EXPECTED = {
    # fill over plain
    ("fill", "plain", "a"): "[(9, 2)]",
    ("fill", "plain", "A"): "[(9, 2)]",
    ("fill", "plain", "t.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "plain", "T.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "plain", "t.A"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "plain", "t.s"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "plain", "t.s.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "plain", "t.s.inner.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "plain", "t.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "plain", "t.s.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "plain", "l.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "plain", "r.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "plain", "r.id"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "plain", "t.n.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    # fill over alias
    ("fill", "alias", "a"): "[(9, 2)]",
    ("fill", "alias", "A"): "[(9, 2)]",
    ("fill", "alias", "t.a"): "[(9, 2)]",
    ("fill", "alias", "T.a"): "[(9, 2)]",
    ("fill", "alias", "t.A"): "[(9, 2)]",
    ("fill", "alias", "t.s"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "alias", "t.s.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "alias", "t.s.inner.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "alias", "t.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "alias", "t.s.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "alias", "l.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "alias", "r.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "alias", "r.id"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "alias", "t.n.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    # fill over shadow
    ("fill", "shadow", "a"): "[((None,), 9, 2)]",
    ("fill", "shadow", "A"): "[((None,), 9, 2)]",
    ("fill", "shadow", "t.a"): "[((None,), 9, 2)]",
    ("fill", "shadow", "T.a"): "[((None,), 9, 2)]",
    ("fill", "shadow", "t.A"): "[((None,), 9, 2)]",
    ("fill", "shadow", "t.s"): "ERR FIELD_NOT_FOUND",
    ("fill", "shadow", "t.s.a"): "ERR FIELD_NOT_FOUND",
    ("fill", "shadow", "t.s.inner.x"): "ERR FIELD_NOT_FOUND",
    ("fill", "shadow", "t.nope"): "ERR FIELD_NOT_FOUND",
    ("fill", "shadow", "t.s.nope"): "ERR FIELD_NOT_FOUND",
    ("fill", "shadow", "l.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "shadow", "r.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "shadow", "r.id"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "shadow", "t.n.x"): "ERR FIELD_NOT_FOUND",
    # fill over struct
    ("fill", "struct", "a"): "[((None, (None,)), 9, 2)]",
    ("fill", "struct", "A"): "[((None, (None,)), 9, 2)]",
    ("fill", "struct", "t.a"): "[((None, (None,)), 9, 2)]",
    ("fill", "struct", "T.a"): "[((None, (None,)), 9, 2)]",
    ("fill", "struct", "t.A"): "[((None, (None,)), 9, 2)]",
    ("fill", "struct", "t.s"): "[((None, (None,)), None, 2)]",
    ("fill", "struct", "t.s.a"): "[((None, (None,)), None, 2)]",
    ("fill", "struct", "t.s.inner.x"): "[((None, (None,)), None, 2)]",
    ("fill", "struct", "t.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "struct", "t.s.nope"): "ERR FIELD_NOT_FOUND",
    ("fill", "struct", "l.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "struct", "r.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "struct", "r.id"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "struct", "t.n.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    # fill over join
    ("fill", "join", "a"): "ERR AMBIGUOUS_REFERENCE",
    ("fill", "join", "A"): "ERR AMBIGUOUS_REFERENCE",
    ("fill", "join", "t.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "join", "T.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "join", "t.A"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "join", "t.s"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "join", "t.s.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "join", "t.s.inner.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "join", "t.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "join", "t.s.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "join", "l.a"): "[(1, 9, 2, None)]",
    ("fill", "join", "r.a"): "[(1, None, 2, 9)]",
    ("fill", "join", "r.id"): "[(1, None, 2, None)]",
    ("fill", "join", "t.n.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    # fill over twice
    ("fill", "twice", "a"): "[(9, 9, 2)]",
    ("fill", "twice", "A"): "[(9, 9, 2)]",
    ("fill", "twice", "t.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "twice", "T.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "twice", "t.A"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "twice", "t.s"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "twice", "t.s.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "twice", "t.s.inner.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "twice", "t.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "twice", "t.s.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "twice", "l.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "twice", "r.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "twice", "r.id"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "twice", "t.n.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    # fill over nullbase
    ("fill", "nullbase", "a"): "[(None, 9, 2)]",
    ("fill", "nullbase", "A"): "[(None, 9, 2)]",
    ("fill", "nullbase", "t.a"): "[(None, 9, 2)]",
    ("fill", "nullbase", "T.a"): "[(None, 9, 2)]",
    ("fill", "nullbase", "t.A"): "[(None, 9, 2)]",
    ("fill", "nullbase", "t.s"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "nullbase", "t.s.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "nullbase", "t.s.inner.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "nullbase", "t.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "nullbase", "t.s.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "nullbase", "l.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "nullbase", "r.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "nullbase", "r.id"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fill", "nullbase", "t.n.x"): "[(None, None, 2)]",
    # fillmap over plain
    ("fillmap", "plain", "a"): "[(9, 2)]",
    ("fillmap", "plain", "A"): "[(9, 2)]",
    ("fillmap", "plain", "t.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "plain", "T.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "plain", "t.A"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "plain", "t.s"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "plain", "t.s.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "plain", "t.s.inner.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "plain", "t.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "plain", "t.s.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "plain", "l.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "plain", "r.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "plain", "r.id"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "plain", "t.n.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    # fillmap over alias
    ("fillmap", "alias", "a"): "[(9, 2)]",
    ("fillmap", "alias", "A"): "[(9, 2)]",
    ("fillmap", "alias", "t.a"): "[(9, 2)]",
    ("fillmap", "alias", "T.a"): "[(9, 2)]",
    ("fillmap", "alias", "t.A"): "[(9, 2)]",
    ("fillmap", "alias", "t.s"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "alias", "t.s.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "alias", "t.s.inner.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "alias", "t.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "alias", "t.s.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "alias", "l.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "alias", "r.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "alias", "r.id"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "alias", "t.n.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    # fillmap over shadow
    ("fillmap", "shadow", "a"): "[((None,), 9, 2)]",
    ("fillmap", "shadow", "A"): "[((None,), 9, 2)]",
    ("fillmap", "shadow", "t.a"): "[((None,), 9, 2)]",
    ("fillmap", "shadow", "T.a"): "[((None,), 9, 2)]",
    ("fillmap", "shadow", "t.A"): "[((None,), 9, 2)]",
    ("fillmap", "shadow", "t.s"): "ERR FIELD_NOT_FOUND",
    ("fillmap", "shadow", "t.s.a"): "ERR FIELD_NOT_FOUND",
    ("fillmap", "shadow", "t.s.inner.x"): "ERR FIELD_NOT_FOUND",
    ("fillmap", "shadow", "t.nope"): "ERR FIELD_NOT_FOUND",
    ("fillmap", "shadow", "t.s.nope"): "ERR FIELD_NOT_FOUND",
    ("fillmap", "shadow", "l.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "shadow", "r.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "shadow", "r.id"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "shadow", "t.n.x"): "ERR FIELD_NOT_FOUND",
    # fillmap over struct
    ("fillmap", "struct", "a"): "[((None, (None,)), 9, 2)]",
    ("fillmap", "struct", "A"): "[((None, (None,)), 9, 2)]",
    ("fillmap", "struct", "t.a"): "[((None, (None,)), 9, 2)]",
    ("fillmap", "struct", "T.a"): "[((None, (None,)), 9, 2)]",
    ("fillmap", "struct", "t.A"): "[((None, (None,)), 9, 2)]",
    ("fillmap", "struct", "t.s"): "ERR DATATYPE_MISMATCH.CAST_WITHOUT_SUGGESTION",
    ("fillmap", "struct", "t.s.a"): "ERR UNSUPPORTED_FEATURE.REPLACE_NESTED_COLUMN",
    ("fillmap", "struct", "t.s.inner.x"): "ERR UNSUPPORTED_FEATURE.REPLACE_NESTED_COLUMN",
    ("fillmap", "struct", "t.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "struct", "t.s.nope"): "ERR FIELD_NOT_FOUND",
    ("fillmap", "struct", "l.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "struct", "r.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "struct", "r.id"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "struct", "t.n.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    # fillmap over join
    ("fillmap", "join", "a"): "ERR AMBIGUOUS_REFERENCE",
    ("fillmap", "join", "A"): "ERR AMBIGUOUS_REFERENCE",
    ("fillmap", "join", "t.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "join", "T.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "join", "t.A"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "join", "t.s"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "join", "t.s.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "join", "t.s.inner.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "join", "t.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "join", "t.s.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "join", "l.a"): "[(1, 9, 2, None)]",
    ("fillmap", "join", "r.a"): "[(1, None, 2, 9)]",
    ("fillmap", "join", "r.id"): "[(1, None, 2, None)]",
    ("fillmap", "join", "t.n.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    # fillmap over twice
    ("fillmap", "twice", "a"): "[(9, 9, 2)]",
    ("fillmap", "twice", "A"): "[(9, 9, 2)]",
    ("fillmap", "twice", "t.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "twice", "T.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "twice", "t.A"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "twice", "t.s"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "twice", "t.s.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "twice", "t.s.inner.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "twice", "t.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "twice", "t.s.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "twice", "l.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "twice", "r.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "twice", "r.id"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "twice", "t.n.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    # fillmap over nullbase
    ("fillmap", "nullbase", "a"): "[(None, 9, 2)]",
    ("fillmap", "nullbase", "A"): "[(None, 9, 2)]",
    ("fillmap", "nullbase", "t.a"): "[(None, 9, 2)]",
    ("fillmap", "nullbase", "T.a"): "[(None, 9, 2)]",
    ("fillmap", "nullbase", "t.A"): "[(None, 9, 2)]",
    ("fillmap", "nullbase", "t.s"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "nullbase", "t.s.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "nullbase", "t.s.inner.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "nullbase", "t.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "nullbase", "t.s.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "nullbase", "l.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "nullbase", "r.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "nullbase", "r.id"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("fillmap", "nullbase", "t.n.x"): "ERR UNSUPPORTED_FEATURE.REPLACE_NESTED_COLUMN",
    # replace over plain
    ("replace", "plain", "a"): "[(7, 2)]",
    ("replace", "plain", "A"): "[(1, 2)]",
    ("replace", "plain", "t.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "plain", "T.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "plain", "t.A"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "plain", "t.s"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "plain", "t.s.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "plain", "t.s.inner.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "plain", "t.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "plain", "t.s.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "plain", "l.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "plain", "r.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "plain", "r.id"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "plain", "t.n.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    # replace over alias
    ("replace", "alias", "a"): "[(7, 2)]",
    ("replace", "alias", "A"): "[(1, 2)]",
    ("replace", "alias", "t.a"): "[(7, 2)]",
    ("replace", "alias", "T.a"): "[(7, 2)]",
    ("replace", "alias", "t.A"): "[(1, 2)]",
    ("replace", "alias", "t.s"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "alias", "t.s.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "alias", "t.s.inner.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "alias", "t.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "alias", "t.s.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "alias", "l.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "alias", "r.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "alias", "r.id"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "alias", "t.n.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    # replace over shadow
    ("replace", "shadow", "a"): "[((1,), 7, 2)]",
    ("replace", "shadow", "A"): "[((1,), 1, 2)]",
    ("replace", "shadow", "t.a"): "[((1,), 7, 2)]",
    ("replace", "shadow", "T.a"): "[((1,), 7, 2)]",
    ("replace", "shadow", "t.A"): "[((1,), 1, 2)]",
    ("replace", "shadow", "t.s"): "ERR FIELD_NOT_FOUND",
    ("replace", "shadow", "t.s.a"): "ERR FIELD_NOT_FOUND",
    ("replace", "shadow", "t.s.inner.x"): "ERR FIELD_NOT_FOUND",
    ("replace", "shadow", "t.nope"): "ERR FIELD_NOT_FOUND",
    ("replace", "shadow", "t.s.nope"): "ERR FIELD_NOT_FOUND",
    ("replace", "shadow", "l.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "shadow", "r.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "shadow", "r.id"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "shadow", "t.n.x"): "ERR FIELD_NOT_FOUND",
    # replace over struct
    ("replace", "struct", "a"): "[((1, (1,)), 7, 2)]",
    ("replace", "struct", "A"): "[((1, (1,)), 1, 2)]",
    ("replace", "struct", "t.a"): "[((1, (1,)), 7, 2)]",
    ("replace", "struct", "T.a"): "[((1, (1,)), 7, 2)]",
    ("replace", "struct", "t.A"): "[((1, (1,)), 1, 2)]",
    ("replace", "struct", "t.s"): "[((1, (1,)), 1, 2)]",
    ("replace", "struct", "t.s.a"): "ERR UNSUPPORTED_FEATURE.REPLACE_NESTED_COLUMN",
    ("replace", "struct", "t.s.inner.x"): "ERR UNSUPPORTED_FEATURE.REPLACE_NESTED_COLUMN",
    ("replace", "struct", "t.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "struct", "t.s.nope"): "ERR FIELD_NOT_FOUND",
    ("replace", "struct", "l.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "struct", "r.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "struct", "r.id"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "struct", "t.n.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    # replace over join
    ("replace", "join", "a"): "ERR AMBIGUOUS_REFERENCE",
    ("replace", "join", "A"): "ERR AMBIGUOUS_REFERENCE",
    ("replace", "join", "t.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "join", "T.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "join", "t.A"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "join", "t.s"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "join", "t.s.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "join", "t.s.inner.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "join", "t.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "join", "t.s.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "join", "l.a"): "[(1, 7, 2, 1)]",
    ("replace", "join", "r.a"): "[(1, 1, 2, 7)]",
    ("replace", "join", "r.id"): "[(1, 1, 2, 1)]",
    ("replace", "join", "t.n.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    # replace over twice
    ("replace", "twice", "a"): "[(7, 7, 2)]",
    ("replace", "twice", "A"): "[(1, 1, 2)]",
    ("replace", "twice", "t.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "twice", "T.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "twice", "t.A"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "twice", "t.s"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "twice", "t.s.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "twice", "t.s.inner.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "twice", "t.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "twice", "t.s.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "twice", "l.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "twice", "r.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "twice", "r.id"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "twice", "t.n.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    # replace over nullbase
    ("replace", "nullbase", "a"): "[(None, 7, 2)]",
    ("replace", "nullbase", "A"): "[(None, 1, 2)]",
    ("replace", "nullbase", "t.a"): "[(None, 7, 2)]",
    ("replace", "nullbase", "T.a"): "[(None, 7, 2)]",
    ("replace", "nullbase", "t.A"): "[(None, 1, 2)]",
    ("replace", "nullbase", "t.s"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "nullbase", "t.s.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "nullbase", "t.s.inner.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "nullbase", "t.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "nullbase", "t.s.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "nullbase", "l.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "nullbase", "r.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "nullbase", "r.id"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("replace", "nullbase", "t.n.x"): "ERR UNSUPPORTED_FEATURE.REPLACE_NESTED_COLUMN",
    # dropna over plain
    ("dropna", "plain", "a"): "[]",
    ("dropna", "plain", "A"): "[]",
    ("dropna", "plain", "t.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "plain", "T.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "plain", "t.A"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "plain", "t.s"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "plain", "t.s.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "plain", "t.s.inner.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "plain", "t.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "plain", "t.s.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "plain", "l.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "plain", "r.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "plain", "r.id"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "plain", "t.n.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    # dropna over alias
    ("dropna", "alias", "a"): "[]",
    ("dropna", "alias", "A"): "[]",
    ("dropna", "alias", "t.a"): "[]",
    ("dropna", "alias", "T.a"): "[]",
    ("dropna", "alias", "t.A"): "[]",
    ("dropna", "alias", "t.s"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "alias", "t.s.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "alias", "t.s.inner.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "alias", "t.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "alias", "t.s.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "alias", "l.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "alias", "r.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "alias", "r.id"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "alias", "t.n.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    # dropna over shadow
    ("dropna", "shadow", "a"): "[]",
    ("dropna", "shadow", "A"): "[]",
    ("dropna", "shadow", "t.a"): "[]",
    ("dropna", "shadow", "T.a"): "[]",
    ("dropna", "shadow", "t.A"): "[]",
    ("dropna", "shadow", "t.s"): "ERR FIELD_NOT_FOUND",
    ("dropna", "shadow", "t.s.a"): "ERR FIELD_NOT_FOUND",
    ("dropna", "shadow", "t.s.inner.x"): "ERR FIELD_NOT_FOUND",
    ("dropna", "shadow", "t.nope"): "ERR FIELD_NOT_FOUND",
    ("dropna", "shadow", "t.s.nope"): "ERR FIELD_NOT_FOUND",
    ("dropna", "shadow", "l.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "shadow", "r.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "shadow", "r.id"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "shadow", "t.n.x"): "ERR FIELD_NOT_FOUND",
    # dropna over struct
    ("dropna", "struct", "a"): "[]",
    ("dropna", "struct", "A"): "[]",
    ("dropna", "struct", "t.a"): "[]",
    ("dropna", "struct", "T.a"): "[]",
    ("dropna", "struct", "t.A"): "[]",
    ("dropna", "struct", "t.s"): "[((None, (None,)), None, 2)]",
    ("dropna", "struct", "t.s.a"): "[]",
    ("dropna", "struct", "t.s.inner.x"): "[]",
    ("dropna", "struct", "t.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "struct", "t.s.nope"): "ERR FIELD_NOT_FOUND",
    ("dropna", "struct", "l.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "struct", "r.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "struct", "r.id"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "struct", "t.n.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    # dropna over join
    ("dropna", "join", "a"): "ERR AMBIGUOUS_REFERENCE",
    ("dropna", "join", "A"): "ERR AMBIGUOUS_REFERENCE",
    ("dropna", "join", "t.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "join", "T.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "join", "t.A"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "join", "t.s"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "join", "t.s.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "join", "t.s.inner.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "join", "t.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "join", "t.s.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "join", "l.a"): "[]",
    ("dropna", "join", "r.a"): "[]",
    ("dropna", "join", "r.id"): "[(1, None, 2, None)]",
    ("dropna", "join", "t.n.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    # dropna over twice
    ("dropna", "twice", "a"): "[]",
    ("dropna", "twice", "A"): "[]",
    ("dropna", "twice", "t.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "twice", "T.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "twice", "t.A"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "twice", "t.s"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "twice", "t.s.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "twice", "t.s.inner.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "twice", "t.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "twice", "t.s.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "twice", "l.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "twice", "r.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "twice", "r.id"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "twice", "t.n.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    # dropna over nullbase
    ("dropna", "nullbase", "a"): "[]",
    ("dropna", "nullbase", "A"): "[]",
    ("dropna", "nullbase", "t.a"): "[]",
    ("dropna", "nullbase", "T.a"): "[]",
    ("dropna", "nullbase", "t.A"): "[]",
    ("dropna", "nullbase", "t.s"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "nullbase", "t.s.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "nullbase", "t.s.inner.x"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "nullbase", "t.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "nullbase", "t.s.nope"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "nullbase", "l.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "nullbase", "r.a"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "nullbase", "r.id"): "ERR UNRESOLVED_COLUMN.WITH_SUGGESTION",
    ("dropna", "nullbase", "t.n.x"): "[]",
}


def _cases():
    for key in _EXPECTED:
        marks = (
            [pytest.mark.xfail(not is_jvm_spark(), reason="Known Sail bug", strict=True)] if key in _SAIL_BUGS else []
        )
        if key[1:] == ("nullbase", "t.n.x"):
            # Before 4.2 Spark refuses to read a field of a NULL base (`ExtractValue.applyOrNull`).
            marks.append(
                pytest.mark.skipif(is_jvm_spark() and pyspark_version() < (4, 2), reason="Spark 4.2 behavior")
            )
        yield pytest.param(*key, id="-".join(key), marks=marks)


@pytest.mark.parametrize(("operation", "frame", "name"), _cases())
def test_a_subset_name(spark, operation, frame, name):
    assert _outcome(spark, operation, frame, name) == _EXPECTED[(operation, frame, name)]
