import pytest
from pyspark.sql import functions as F
from pyspark.sql.types import IntegerType, MapType, StringType, StructField, StructType


def test_predicate_negation(spark):
    assert spark.sql("SELECT NOT '' LIKE '%'").collect() == [(False,)]
    assert spark.sql("SELECT NOT ('' LIKE '%')").collect() == [(False,)]
    assert spark.sql("SELECT '' NOT LIKE '%'").collect() == [(False,)]

    assert spark.sql("SELECT NOT 1 BETWEEN 1 AND 2").collect() == [(False,)]
    assert spark.sql("SELECT NOT (1 BETWEEN 1 AND 2)").collect() == [(False,)]
    assert spark.sql("SELECT 1 NOT BETWEEN 1 AND 2").collect() == [(False,)]

    assert spark.sql("SELECT NOT 'a' IS NULL").collect() == [(True,)]
    assert spark.sql("SELECT NOT ('a' IS NULL)").collect() == [(True,)]
    assert spark.sql("SELECT 'a' IS NOT NULL").collect() == [(True,)]

    assert spark.sql("SELECT NOT 1 IN (1, 2)").collect() == [(False,)]
    assert spark.sql("SELECT NOT (1 IN (1, 2))").collect() == [(False,)]
    assert spark.sql("SELECT 1 NOT IN (1, 2)").collect() == [(False,)]

    assert spark.sql("SELECT NOT NOT 1 IN (1, 2)").collect() == [(True,)]
    assert spark.sql("SELECT NOT 1 NOT IN (1, 2)").collect() == [(True,)]
    assert spark.sql("SELECT NOT (1 NOT IN (1, 2))").collect() == [(True,)]
    with pytest.raises(Exception, match="NOT"):
        assert spark.sql("SELECT 1 NOT NOT IN (1, 2)").collect() == [(True,)]


def test_values_map_schema_nullability(spark):
    query = """
        SELECT * FROM VALUES
        (MAP('a', 'ab'), MAP('a', 'ab'), MAP(1, 2, 3, 4)),
        (MAP('x', 'yz'), MAP('x', NULL), NULL),
        (MAP('c', 'de'), NULL, MAP(-1, NULL, -3, -4))
        AS tab(a, b, c)
    """

    assert spark.sql(query).schema == StructType(
        [
            StructField("a", MapType(StringType(), StringType(), False), False),
            StructField("b", MapType(StringType(), StringType(), True), True),
            StructField("c", MapType(IntegerType(), IntegerType(), True), True),
        ]
    )


def test_auto_generated_alias_metadata(spark):
    schema = spark.sql("SELECT STRUCT(1)").schema

    assert schema[0].metadata == {"__autoGeneratedAlias": "true"}


def test_sql_parameter_args(spark):
    positional = spark.sql(
        "SELECT *, element_at(?, 1) FROM range(10) WHERE id > ?",
        args=[F.array(F.lit(1)), 7],
    ).collect()
    named = spark.sql(
        "SELECT *, element_at(:m, 'a') FROM range(10) WHERE id > :minId",
        args={"m": F.create_map(F.lit("a"), F.lit(1)), "minId": 7},
    ).collect()

    assert [tuple(row) for row in positional] == [(8, 1), (9, 1)]
    assert [tuple(row) for row in named] == [(8, 1), (9, 1)]
