name: Match commit message
description: Match the commit message against a pattern
inputs:
  pattern:
    description: The Node.js regular expression to match against the commit message
    type: string
    required: true
  ignore_case:
    description: Whether to ignore the case when matching the pattern
    type: boolean
    default: false
outputs:
  result:
    description: "'true' if the commit message matches the pattern, or 'false' otherwise"
    value: ${{ steps.match.outputs.result }}
runs:
  using: composite
  steps:
    - id: match
      uses: actions/github-script@v7
      env:
        MESSAGE_PATTERN: ${{ inputs.pattern }}
        MESSAGE_FLAGS: ${{ inputs.ignore_case && 'i' || '' }}
      with:
        result-encoding: string
        script: |
          const { data: commit } = await github.rest.git.getCommit({
            owner: context.repo.owner,
            repo: context.repo.repo,
            // When the event is `pull_request`, we must extract the commit message from the head branch,
            // rather than the merge branch created by GitHub.
            commit_sha: context.payload.pull_request !== null ? context.payload.pull_request.head.sha : context.sha,
          });
          const pattern = process.env.MESSAGE_PATTERN;
          const flags = process.env.MESSAGE_FLAGS;
          const regex = new RegExp(pattern, flags);
          return commit.message.match(regex) !== null ? 'true' : 'false';
