[tool.poetry]
name = "pyspark-sql"
version = "0.0.1"
description = "PySpark code sample for Spark Connect"
authors = ["LakeSail <hello@lakesail.com>"]
readme = "README.md"
license = "Apache-2.0"
packages = [{ include = "app", from = "src" }]

[tool.poetry.dependencies]
python = "~3.10"
pyspark = { version = "^3.5.0", extras = ["connect"] }

[tool.poetry.group.dev.dependencies]
isort = "^5.12.0"
black = "^23.12.1"
flake8 = "^7.0.0"

[tool.black]
line-length = 100

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
