// GSSAPI bindings module
// Generated by `bindgen` from the system GSSAPI headers (`gssapi.h`).
// To regenerate (e.g. for a newer GSSAPI version):
//   bindgen /usr/include/gssapi.h -o src/security/gssapi_bindings.rs
// The generated bindings are checked in because the build environment may not have bindgen installed.
// The bindings are portable across architectures because the GSSAPI C ABI uses only standard types
// (u32 constants, *mut c_void pointers, usize lengths) that adapt to the host automatically.
//
// The Kerberos/GSSAPI session implementation was inspired by the hdfs-native project
// (https://github.com/Kimahriman/hdfs-native), licensed under the Apache License 2.0.
mod gssapi;
mod thrift_sasl;

pub(crate) use gssapi::SaslQop;
pub(crate) use thrift_sasl::KerberosMakeTransport;

/// Returns `true` if the GSSAPI/Kerberos runtime library is available on this host.
pub fn gssapi_available() -> bool {
    gssapi::is_available()
}
