[package]
name = "sail-sql"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
sail-common = { path = "../sail-common" }

thiserror = { workspace = true }
datafusion = { workspace = true }
sqlparser = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
lazy_static = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
