/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AssertViewUuid : The view UUID must match the requirement's `uuid`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssertViewUuid {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "uuid")]
    pub uuid: String,
}

impl AssertViewUuid {
    /// The view UUID must match the requirement's `uuid`
    pub fn new(r#type: Type, uuid: String) -> AssertViewUuid {
        AssertViewUuid {
            r#type,
            uuid,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "assert-view-uuid")]
    AssertViewUuid,
}

impl Default for Type {
    fn default() -> Type {
        Self::AssertViewUuid
    }
}

