/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "content")]
pub enum DeleteFile {
    #[serde(rename="position-deletes")]
    PositionDeletes(Box<models::PositionDeleteFile>),
    #[serde(rename="equality-deletes")]
    EqualityDeletes(Box<models::EqualityDeleteFile>),
}

impl Default for DeleteFile {
    fn default() -> Self {
        Self::PositionDeletes(Default::default())
    }
}


