/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoadCredentialsResponse {
    #[serde(rename = "storage-credentials")]
    pub storage_credentials: Vec<models::StorageCredential>,
}

impl LoadCredentialsResponse {
    pub fn new(storage_credentials: Vec<models::StorageCredential>) -> LoadCredentialsResponse {
        LoadCredentialsResponse {
            storage_credentials,
        }
    }
}

