[package]
name = "sail-streaming"
version = { workspace = true }
edition = { workspace = true }

[lints]
workspace = true

[dependencies]
datafusion = { workspace = true }
datafusion-common = { workspace = true }
datafusion-expr = { workspace = true }
chrono = { workspace = true }
prost = { workspace = true }
tonic = { workspace = true }
futures = { workspace = true }
pin-project-lite = { workspace = true }
log = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true }
