== Physical Plan ==
ProjectionExec: expr=[#4@0 as k, #5@1 as SUM(v)], statistics=[Rows=Inexact(2), Bytes=Inexact(<bytes>), [(Col[0]:),(Col[1]:)]], schema=[k:Int32;N, SUM(v):Int64;N]
  ProjectionExec: expr=[#2@0 as #4, sum(t.#3)@1 as #5], statistics=[Rows=Inexact(2), Bytes=Inexact(<bytes>), [(Col[0]:),(Col[1]:)]], schema=[#4:Int32;N, #5:Int64;N]
    AggregateExec: mode=FinalPartitioned, gby=[#2@0 as #2], aggr=[sum(t.#3)], statistics=[Rows=Inexact(2), Bytes=Absent, [(Col[0]:),(Col[1]:)]], schema=[#2:Int32;N, sum(t.#3):Int64;N]
      CoalesceBatchesExec: target_batch_size=8192, statistics=[Rows=Inexact(2), Bytes=Absent, [(Col[0]:),(Col[1]:)]], schema=[#2:Int32;N, sum(t.#3)[sum]:Int64;N]
        RepartitionExec: partitioning=Hash([#2@0], <partitions>), input_partitions=<partitions>, statistics=[Rows=Inexact(2), Bytes=Absent, [(Col[0]:),(Col[1]:)]], schema=[#2:Int32;N, sum(t.#3)[sum]:Int64;N]
          RepartitionExec: partitioning=RoundRobinBatch(<partitions>), input_partitions=<partitions>, statistics=[Rows=Inexact(2), Bytes=Absent, [(Col[0]:),(Col[1]:)]], schema=[#2:Int32;N, sum(t.#3)[sum]:Int64;N]
            AggregateExec: mode=Partial, gby=[#2@0 as #2], aggr=[sum(t.#3)], statistics=[Rows=Inexact(2), Bytes=Absent, [(Col[0]:),(Col[1]:)]], schema=[#2:Int32;N, sum(t.#3)[sum]:Int64;N]
              ProjectionExec: expr=[column1@0 as #2, column2@1 as #3], statistics=[Rows=Exact(2), Bytes=Exact(<bytes>), [(Col[0]: Null=Exact(0)),(Col[1]: Null=Exact(0))]], schema=[#2:Int32;N, #3:Int32;N]
                DataSourceExec: partitions=1, partition_sizes=[<sizes>], statistics=[Rows=Exact(2), Bytes=Exact(<bytes>), [(Col[0]: Null=Exact(0)),(Col[1]: Null=Exact(0))]], schema=[column1:Int32;N, column2:Int32;N]