[package]
name = "sail-python"
version = { workspace = true }
edition = { workspace = true }

[lints]
workspace = true

[features]
mimalloc = ["dep:mimalloc"]

[dependencies]
sail-common = { path = "../sail-common" }
sail-common-datafusion = { path = "../sail-common-datafusion" }
sail-telemetry = { path = "../sail-telemetry" }
sail-flight = { path = "../sail-flight" }
sail-spark-connect = { path = "../sail-spark-connect" }
sail-cli = { path = "../sail-cli" }
sail-celeborn = { path = "../sail-celeborn" }
sail-catalog = { path = "../sail-catalog" }
sail-catalog-glue = { path = "../sail-catalog-glue" }
sail-catalog-hms = { path = "../sail-catalog-hms" }
sail-catalog-iceberg = { path = "../sail-catalog-iceberg" }
sail-catalog-unity = { path = "../sail-catalog-unity" }

arrow-schema = { workspace = true }
bytes = { workspace = true }
# TODO: Drop "v2" after:
#       - libmimalloc-sys vendors the fix for https://github.com/microsoft/mimalloc/issues/1287 and
#       - exposes MI_TLS_MODEL_LOCAL for macOS coexistence https://github.com/microsoft/mimalloc/issues/1301
mimalloc = { workspace = true, optional = true, features = ["local_dynamic_tls", "v2"] }
pyo3 = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
fastrace = { workspace = true }
futures = { workspace = true }

[lib]
crate-type = ["cdylib"]
