[package]
name = "sail-python"
version = { workspace = true }
edition = { workspace = true }

[lints]
workspace = true

[dependencies]
sail-common = { path = "../sail-common" }
sail-common-datafusion = { path = "../sail-common-datafusion" }
sail-telemetry = { path = "../sail-telemetry" }
sail-flight = { path = "../sail-flight" }
sail-spark-connect = { path = "../sail-spark-connect" }
sail-cli = { path = "../sail-cli" }
sail-celeborn = { path = "../sail-celeborn" }
sail-catalog = { path = "../sail-catalog" }
sail-catalog-glue = { path = "../sail-catalog-glue" }
sail-catalog-hms = { path = "../sail-catalog-hms" }
sail-catalog-iceberg = { path = "../sail-catalog-iceberg" }

arrow-schema = { workspace = true }
bytes = { workspace = true }
pyo3 = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
fastrace = { workspace = true }
futures = { workspace = true }

[lib]
crate-type = ["cdylib"]
