/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

/// AssertDefaultSpecId : The table's default spec id must match the requirement's `default-spec-id`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssertDefaultSpecId {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "default-spec-id")]
    pub default_spec_id: i32,
}

impl AssertDefaultSpecId {
    /// The table's default spec id must match the requirement's `default-spec-id`
    pub fn new(default_spec_id: i32) -> AssertDefaultSpecId {
        AssertDefaultSpecId {
            r#type: None,
            default_spec_id,
        }
    }
}
