/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

/// AssertLastAssignedFieldId : The table's last assigned column id must match the requirement's `last-assigned-field-id`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssertLastAssignedFieldId {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "last-assigned-field-id")]
    pub last_assigned_field_id: i32,
}

impl AssertLastAssignedFieldId {
    /// The table's last assigned column id must match the requirement's `last-assigned-field-id`
    pub fn new(last_assigned_field_id: i32) -> AssertLastAssignedFieldId {
        AssertLastAssignedFieldId {
            r#type: None,
            last_assigned_field_id,
        }
    }
}
