/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

/// AssertCreate : The table must not already exist; used for create transactions
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssertCreate {
    #[serde(rename = "type")]
    pub r#type: String,
}

impl AssertCreate {
    /// The table must not already exist; used for create transactions
    pub fn new(r#type: String) -> AssertCreate {
        AssertCreate { r#type }
    }
}
