/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NullOrder {
    #[serde(rename = "nulls-first")]
    NullsFirst,
    #[serde(rename = "nulls-last")]
    NullsLast,
}

impl std::fmt::Display for NullOrder {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::NullsFirst => write!(f, "nulls-first"),
            Self::NullsLast => write!(f, "nulls-last"),
        }
    }
}

impl Default for NullOrder {
    fn default() -> NullOrder {
        Self::NullsFirst
    }
}
