/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemoveSnapshotRefUpdate {
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<String>,
    #[serde(rename = "ref-name")]
    pub ref_name: String,
}

impl RemoveSnapshotRefUpdate {
    pub fn new(ref_name: String) -> RemoveSnapshotRefUpdate {
        RemoveSnapshotRefUpdate {
            action: None,
            ref_name,
        }
    }
}
