/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SortOrder {
    #[serde(rename = "order-id")]
    pub order_id: i32,
    #[serde(rename = "fields")]
    pub fields: Vec<models::SortField>,
}

impl SortOrder {
    pub fn new(order_id: i32, fields: Vec<models::SortField>) -> SortOrder {
        SortOrder { order_id, fields }
    }
}
