/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SqlViewRepresentation {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "sql")]
    pub sql: String,
    #[serde(rename = "dialect")]
    pub dialect: String,
}

impl SqlViewRepresentation {
    pub fn new(r#type: String, sql: String, dialect: String) -> SqlViewRepresentation {
        SqlViewRepresentation {
            r#type,
            sql,
            dialect,
        }
    }
}
