// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "action")]
pub enum TableUpdate {
    #[serde(rename = "add-encryption-key")]
    AddEncryptionKeyUpdate {
        #[serde(rename = "encryption-key")]
        encryption_key: Box<models::EncryptedKey>,
    },
    #[serde(rename = "add-schema")]
    AddSchemaUpdate {
        #[serde(rename = "schema")]
        schema: Box<models::Schema>,
        #[serde(rename = "last-column-id", skip_serializing_if = "Option::is_none")]
        last_column_id: Option<i32>,
    },
    #[serde(rename = "add-snapshot")]
    AddSnapshotUpdate {
        #[serde(rename = "snapshot")]
        snapshot: Box<models::Snapshot>,
    },
    #[serde(rename = "add-sort-order")]
    AddSortOrderUpdate {
        #[serde(rename = "sort-order")]
        sort_order: Box<models::SortOrder>,
    },
    #[serde(rename = "add-spec")]
    AddPartitionSpecUpdate {
        #[serde(rename = "spec")]
        spec: Box<models::PartitionSpec>,
    },
    #[serde(rename = "assign-uuid")]
    AssignUuidUpdate { uuid: String },
    #[serde(rename = "remove-encryption-key")]
    RemoveEncryptionKeyUpdate {
        #[serde(rename = "key-id")]
        key_id: String,
    },
    #[serde(rename = "remove-partition-specs")]
    RemovePartitionSpecsUpdate {
        #[serde(rename = "spec-ids")]
        spec_ids: Vec<i32>,
    },
    #[serde(rename = "remove-partition-statistics")]
    RemovePartitionStatisticsUpdate {
        #[serde(rename = "snapshot-id")]
        snapshot_id: i64,
    },
    #[serde(rename = "remove-properties")]
    RemovePropertiesUpdate { removals: Vec<String> },
    #[serde(rename = "remove-schemas")]
    RemoveSchemasUpdate {
        #[serde(rename = "schema-ids")]
        schema_ids: Vec<i32>,
    },
    #[serde(rename = "remove-snapshot-ref")]
    RemoveSnapshotRefUpdate {
        #[serde(rename = "ref-name")]
        ref_name: String,
    },
    #[serde(rename = "remove-snapshots")]
    RemoveSnapshotsUpdate {
        #[serde(rename = "snapshot-ids")]
        snapshot_ids: Vec<i64>,
    },
    #[serde(rename = "remove-statistics")]
    RemoveStatisticsUpdate {
        #[serde(rename = "snapshot-id")]
        snapshot_id: i64,
    },
    #[serde(rename = "set-current-schema")]
    SetCurrentSchemaUpdate {
        #[serde(rename = "schema-id")]
        schema_id: i32,
    },
    #[serde(rename = "set-default-sort-order")]
    SetDefaultSortOrderUpdate {
        #[serde(rename = "sort-order-id")]
        sort_order_id: i64,
    },
    #[serde(rename = "set-default-spec")]
    SetDefaultSpecUpdate {
        #[serde(rename = "spec-id")]
        spec_id: i32,
    },
    #[serde(rename = "set-location")]
    SetLocationUpdate { location: String },
    #[serde(rename = "set-partition-statistics")]
    SetPartitionStatisticsUpdate {
        #[serde(rename = "partition-statistics")]
        partition_statistics: Box<models::PartitionStatisticsFile>,
    },
    #[serde(rename = "set-properties")]
    SetPropertiesUpdate {
        updates: std::collections::HashMap<String, String>,
    },
    #[serde(rename = "set-snapshot-ref")]
    SetSnapshotRefUpdate {
        #[serde(rename = "ref-name")]
        ref_name: String,
        #[serde(rename = "type")]
        r#type: models::set_snapshot_ref_update::Type,
        #[serde(rename = "snapshot-id")]
        snapshot_id: i64,
        #[serde(rename = "max-ref-age-ms", skip_serializing_if = "Option::is_none")]
        max_ref_age_ms: Option<i64>,
        #[serde(
            rename = "max-snapshot-age-ms",
            skip_serializing_if = "Option::is_none"
        )]
        max_snapshot_age_ms: Option<i64>,
        #[serde(
            rename = "min-snapshots-to-keep",
            skip_serializing_if = "Option::is_none"
        )]
        min_snapshots_to_keep: Option<i32>,
    },
    #[serde(rename = "set-statistics")]
    SetStatisticsUpdate {
        #[serde(rename = "snapshot-id", skip_serializing_if = "Option::is_none")]
        snapshot_id: Option<i64>,
        statistics: Box<models::StatisticsFile>,
    },
    #[serde(rename = "upgrade-format-version")]
    UpgradeFormatVersionUpdate {
        #[serde(rename = "format-version")]
        format_version: i32,
    },
}

impl Default for TableUpdate {
    fn default() -> Self {
        Self::SetPropertiesUpdate {
            updates: Default::default(),
        }
    }
}
