// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "action", rename_all = "kebab-case")]
pub enum TableUpdate {
    UpgradeFormatVersion {
        #[serde(rename = "format-version")]
        format_version: i32,
    },
    AssignUuid {
        uuid: Uuid,
    },
    AddSchema {
        schema: Box<models::Schema>,
        #[serde(rename = "last-column-id", skip_serializing_if = "Option::is_none")]
        last_column_id: Option<i32>,
    },
    SetCurrentSchema {
        #[serde(rename = "schema-id")]
        schema_id: i32,
    },
    AddSpec {
        spec: Box<models::PartitionSpec>,
    },
    SetDefaultSpec {
        #[serde(rename = "spec-id")]
        spec_id: i32,
    },
    AddSortOrder {
        #[serde(rename = "sort-order")]
        sort_order: Box<models::SortOrder>,
    },
    SetDefaultSortOrder {
        #[serde(rename = "sort-order-id")]
        sort_order_id: i64,
    },
    AddSnapshot {
        snapshot: Box<models::Snapshot>,
    },
    SetSnapshotRef {
        #[serde(rename = "ref-name")]
        ref_name: String,
        #[serde(flatten)]
        reference: models::SnapshotReference,
    },
    RemoveSnapshots {
        #[serde(rename = "snapshot-ids")]
        snapshot_ids: Vec<i64>,
    },
    RemoveSnapshotRef {
        #[serde(rename = "ref-name")]
        ref_name: String,
    },
    SetLocation {
        location: String,
    },
    SetProperties {
        updates: std::collections::HashMap<String, String>,
    },
    RemoveProperties {
        removals: Vec<String>,
    },
    RemovePartitionSpecs {
        #[serde(rename = "spec-ids")]
        spec_ids: Vec<i32>,
    },
    SetStatistics {
        statistics: Box<models::StatisticsFile>,
    },
    RemoveStatistics {
        #[serde(rename = "snapshot-id")]
        snapshot_id: i64,
    },
    SetPartitionStatistics {
        #[serde(rename = "partition-statistics")]
        partition_statistics: Box<models::PartitionStatisticsFile>,
    },
    RemovePartitionStatistics {
        #[serde(rename = "snapshot-id")]
        snapshot_id: i64,
    },
    AddEncryptionKey {
        #[serde(rename = "encryption-key")]
        encryption_key: Box<models::EncryptedKey>,
    },
    RemoveEncryptionKey {
        #[serde(rename = "key-id")]
        key_id: String,
    },
    RemoveSchemas {
        #[serde(rename = "schema-ids")]
        schema_ids: Vec<i32>,
    },
}

#[cfg(test)]
mod tests {
    use super::TableUpdate;
    use crate::models::{snapshot_reference, SnapshotReference};

    #[test]
    fn set_snapshot_ref_serializes_with_tagged_action() {
        let update = TableUpdate::SetSnapshotRef {
            ref_name: "feature".to_string(),
            reference: SnapshotReference {
                r#type: snapshot_reference::Type::Branch,
                snapshot_id: 42,
                max_ref_age_ms: Some(1000),
                max_snapshot_age_ms: Some(2000),
                min_snapshots_to_keep: Some(3),
            },
        };

        #[expect(clippy::expect_used)]
        let json = serde_json::to_value(update).expect("serialize update");
        assert_eq!(json["action"], "set-snapshot-ref");
        assert_eq!(json["ref-name"], "feature");
        assert_eq!(json["type"], "branch");
        assert_eq!(json["snapshot-id"], 42);
        assert_eq!(json["max-ref-age-ms"], 1000);
        assert_eq!(json["max-snapshot-age-ms"], 2000);
        assert_eq!(json["min-snapshots-to-keep"], 3);
    }
}
