// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "action")]
pub enum ViewUpdate {
    #[serde(rename = "add-schema")]
    AddSchemaUpdate {
        #[serde(rename = "schema")]
        schema: Box<models::Schema>,
        #[serde(rename = "last-column-id", skip_serializing_if = "Option::is_none")]
        last_column_id: Option<i32>,
    },
    #[serde(rename = "add-view-version")]
    AddViewVersionUpdate {
        #[serde(rename = "view-version")]
        view_version: Box<models::ViewVersion>,
    },
    #[serde(rename = "assign-uuid")]
    AssignUuidUpdate { uuid: String },
    #[serde(rename = "remove-properties")]
    RemovePropertiesUpdate { removals: Vec<String> },
    #[serde(rename = "set-current-view-version")]
    SetCurrentViewVersionUpdate {
        #[serde(rename = "view-version-id")]
        view_version_id: i32,
    },
    #[serde(rename = "set-location")]
    SetLocationUpdate { location: String },
    #[serde(rename = "set-properties")]
    SetPropertiesUpdate {
        updates: std::collections::HashMap<String, String>,
    },
    #[serde(rename = "upgrade-format-version")]
    UpgradeFormatVersionUpdate {
        #[serde(rename = "format-version")]
        format_version: i32,
    },
}

impl Default for ViewUpdate {
    fn default() -> Self {
        Self::SetPropertiesUpdate {
            updates: Default::default(),
        }
    }
}
