"""Regression tests for interoperability with column-mapped tables written by delta-spark.

The fixture table in ``data/delta_spark_column_mapping`` was generated by
delta-spark 4.3.0 (JVM) with ``delta.columnMapping.mode = 'name'`` set at
creation time, so every field — plain and nested — has a UUID-based physical
parquet name (``col-...``) that differs from its logical name. On top of
that, a plain column (``label`` -> ``code``) and a nested struct field
(``details.amount`` -> ``details.total``) were renamed after the first
insert, so the two parquet data files disagree on field ids as well.

Sail's own writer assigns physical names that stay consistent within a
session, so these delta-spark-generated files are what actually exercises
matching nested fields by ``delta.columnMapping.physicalName`` and column id
instead of by logical name.

The fixture was created with:

    CREATE TABLE delta.`...` (
        id INT, label STRING, details STRUCT<amount: INT, active: BOOLEAN>
    ) USING delta TBLPROPERTIES ('delta.columnMapping.mode' = 'name',
        'delta.minReaderVersion' = '2', 'delta.minWriterVersion' = '5');
    INSERT INTO ... VALUES (1, 'alpha', named_struct('amount', 10, 'active', true)),
                           (2, 'beta', named_struct('amount', 20, 'active', false));
    ALTER TABLE ... RENAME COLUMN label TO code;
    ALTER TABLE ... RENAME COLUMN details.amount TO total;
    INSERT INTO ... VALUES (3, 'gamma', named_struct('total', 30, 'active', true));
"""

from __future__ import annotations

import shutil
from pathlib import Path
from typing import TYPE_CHECKING

import pytest
from pyspark.sql import Row
from pyspark.sql import functions as F  # noqa: N812

from pysail.tests.spark.delta.test_delta_column_mapping import _latest_metadata

if TYPE_CHECKING:
    from pyspark.sql import SparkSession

FIXTURE = Path(__file__).parent / "data" / "delta_spark_column_mapping"

EXPECTED_ROWS = [
    {"id": 1, "code": "alpha", "details": {"total": 10, "active": True}},
    {"id": 2, "code": "beta", "details": {"total": 20, "active": False}},
    {"id": 3, "code": "gamma", "details": {"total": 30, "active": True}},
]


@pytest.fixture
def table_path(tmp_path: Path) -> Path:
    """A scratch copy of the delta-spark fixture table, safe to write to."""
    path = tmp_path / "delta_spark_column_mapping"
    shutil.copytree(FIXTURE, path)
    return path


def _collect(df) -> list[dict]:
    return sorted(
        (row.asDict(recursive=True) for row in df.collect()),
        key=lambda row: row["id"],
    )


def test_read_delta_spark_table_with_renamed_plain_and_nested_fields(spark: SparkSession):
    df = spark.read.format("delta").load(str(FIXTURE))
    assert _collect(df) == EXPECTED_ROWS

    assert sorted(r.code for r in df.select("code").collect()) == ["alpha", "beta", "gamma"]
    assert sorted(r.total for r in df.select("details.total").collect()) == [10, 20, 30]
    assert _collect(df.where(F.col("details.total") > F.lit(15)).select("id", "details")) == [
        {"id": 2, "details": {"total": 20, "active": False}},
        {"id": 3, "details": {"total": 30, "active": True}},
    ]


def test_append_to_delta_spark_table(spark: SparkSession, table_path: Path):
    rows = [Row(id=4, code="delta", details=Row(total=40, active=False))]
    spark.createDataFrame(rows).write.format("delta").mode("append").save(str(table_path))

    df = spark.read.format("delta").load(str(table_path))
    assert _collect(df) == [
        *EXPECTED_ROWS,
        {"id": 4, "code": "delta", "details": {"total": 40, "active": False}},
    ]
    assert sorted(r.total for r in df.select("details.total").collect()) == [10, 20, 30, 40]

    schema_string = _latest_metadata(table_path)["schemaString"]
    assert "PARQUET:field_id" not in schema_string
    assert "parquet.field.id" not in schema_string


def test_overwrite_delta_spark_table_preserves_mapping(spark: SparkSession, table_path: Path):
    original_schema = _latest_metadata(table_path)["schemaString"]

    loaded = spark.read.format("delta").load(str(FIXTURE))
    loaded.where(F.col("id") < F.lit(3)).write.format("delta").mode("overwrite").save(str(table_path))

    df = spark.read.format("delta").load(str(table_path))
    assert _collect(df) == EXPECTED_ROWS[:2]
    assert _latest_metadata(table_path)["schemaString"] == original_schema


def test_rewrite_delta_spark_struct_into_new_table(spark: SparkSession, tmp_path: Path):
    output_path = tmp_path / "rewritten"
    loaded = spark.read.format("delta").load(str(FIXTURE))
    (
        loaded.select("id", "details")
        .write.format("delta")
        .mode("overwrite")
        .option("delta.columnMapping.mode", "name")
        .save(str(output_path))
    )

    df = spark.read.format("delta").load(str(output_path))
    assert _collect(df) == [{"id": row["id"], "details": row["details"]} for row in EXPECTED_ROWS]
    assert sorted(r.total for r in df.select("details.total").collect()) == [10, 20, 30]

    schema_string = _latest_metadata(output_path)["schemaString"]
    assert "PARQUET:field_id" not in schema_string
    assert "parquet.field.id" not in schema_string
