name: Analyze gold data

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/commit-info
        id: info

      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          path: tmp/before
          ref: ${{ info.outputs.sha_before }}

      - uses: actions/checkout@v4
        with:
          path: tmp/after
          ref: ${{ info.outputs.sha_after }}

      - name: Generate gold data report
        run: |
          scripts/common-gold-data/report.sh tmp/after tmp/before > tmp/report.md
          cat tmp/report.md >> "$GITHUB_STEP_SUMMARY"

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: gold-data-report
          path: tmp/report.md
          retention-days: 1

  report:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    needs:
      - run
    steps:
      - name: Download report
        uses: actions/download-artifact@v4
        with:
          name: gold-data-report
          path: tmp

      - name: Publish report
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: gold-data-report
          path: tmp/report.md
