name: Docs release

on:
  workflow_call:
    inputs:
      stage:
        description: The stage ("dev" or "prod") for documentation release
        type: string
        required: true
      version:
        description: The documentation version ("main", "latest", or a version number)
        type: string
        required: true

env:
  RELEASE_ENVIRONMENT: docs/${{ inputs.stage }}
  RELEASE_ARTIFACT_NAME: docs-dist-${{ inputs.stage }}
  RELEASE_SITE_URL: "https://${{ inputs.stage == 'prod' && 'docs' || 'docs.dev' }}.lakesail.com/sail/${{ inputs.version }}/"

jobs:
  build:
    name: Build
    uses: ./.github/workflows/docs-build.yml
    with:
      environment: ${{ env.RELEASE_ENVIRONMENT }}
      artifact_name: ${{ env.RELEASE_ARTIFACT_NAME }}
      site_url: ${{ env.RELEASE_SITE_URL }}

  deploy:
    name: Deploy
    uses: ./.github/workflows/docs-deploy.yml
    permissions:
      id-token: write
    needs:
      - build
    with:
      environment: ${{ env.RELEASE_ENVIRONMENT }}
      artifact_name: ${{ env.RELEASE_ARTIFACT_NAME }}
      site_url: ${{ env.RELEASE_SITE_URL }}
