name: Docs release

on:
  workflow_call:
    inputs:
      stage:
        description: The stage ("dev" or "prod") for documentation release
        type: string
        required: true
      version:
        description: The documentation version ("main", "latest", or a version number)
        type: string
        required: true

jobs:
  build:
    name: Build
    uses: ./.github/workflows/docs-build.yml
    with:
      environment: docs/${{ inputs.stage }}
      artifact_name: docs-dist-${{ inputs.stage }}
      site_url: "https://${{ inputs.stage == 'prod' && 'docs' || 'docs.dev' }}.lakesail.com/sail/${{ inputs.version }}/"

  deploy:
    name: Deploy
    uses: ./.github/workflows/docs-deploy.yml
    permissions:
      id-token: write
    needs:
      - build
    with:
      environment: docs/${{ inputs.stage }}
      artifact_name: docs-dist-${{ inputs.stage }}
      site_url: "https://${{ inputs.stage == 'prod' && 'docs' || 'docs.dev' }}.lakesail.com/sail/${{ inputs.version }}/"
